# Pandas

In [1]:
# two datatype 
# 1. series
# 2. dataframe

In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("st.csv")
df

     id     name  age gender  marks branch
0     1      Ram   24      m     95  civil
1     2    Shyam   23      m     80    eee
2     3     Sita   20      f     85     cs
3     4    Geeta   21      f     93    eee
4     5    Kamal   18      m     77     me
..  ...      ...  ...    ...    ...    ...
95   96    Sneha   32      f     59    eee
96   97    Sumit   34      m     50  civil
97   98  Aarunya   21      f     88  civil
98   99  Atharva   20      m     90     me
99  100    Kowid   21      m     92  civil

[100 rows x 6 columns]

In [8]:
type(df)

pandas.core.frame.DataFrame

In [11]:
x=[1,2,3,4,5]
a=np.array(x)
a

array([1, 2, 3, 4, 5])

In [12]:
type(a)

numpy.ndarray

In [13]:
a[0]

1

In [14]:
a[3]

4

In [15]:
x=[1,2,3,4,5]

s=pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
type(s)

pandas.core.series.Series

In [17]:
s[0]

1

In [18]:
s[4]

5

In [19]:
# series is 1d labelled array 

x=[1,2,3,4,5]

s=pd.Series(x, index=["a", "b", "c", "d", "e"])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [21]:
s["a"]

1

In [24]:
s["e"]

5

In [26]:
# df.values

In [27]:
df.head()

   id   name  age gender  marks branch
0   1    Ram   24      m     95  civil
1   2  Shyam   23      m     80    eee
2   3   Sita   20      f     85     cs
3   4  Geeta   21      f     93    eee
4   5  Kamal   18      m     77     me

In [28]:
# | `df.head()`                                         | `df.values`                                |
# | --------------------------------------------------- | ------------------------------------------ |
# | Shows the first 5 rows of a DataFrame (by default). | Returns all the data as a NumPy array.     |
# | Keeps row and column labels.                        | Does **not** include row or column labels. |
# | Used to preview data.                               | Used when you need only the raw values.    |
# | Output is a **DataFrame**.                          | Output is a **NumPy ndarray**.             |

In [2]:
# series -> 1D labelled array 
#dataframe -> 2D labelled array 

# or say 
# dataframe -> collection of series
# series + series -> dataframe

In [18]:
df1 = pd.read_excel("excel1.xlsx")
df1

,season,id,name,short_name,description,home_team,away_team,toss_won,decision,1st_inning_score,...,away_wickets,away_boundaries,highlights,home_key_batsman,home_key_bowler,home_playx1,away_playx1,away_key_batsman,away_key_bowler,match_days
0,IPL-2023,1359544,Royal Challengers Bangalore v Gujarat Titans,RCB v GT,"70th Match (N), Indian Premier League at Benga...",RCB,GT,GT,BOWL FIRST,197/5,...,4.0,25.0,Gill's second straight century trumps Kohli's ...,"Virat Kohli,Faf du Plessis","Mohammed Siraj,Harshal Patel","Virat Kohli (UKN),Faf du Plessis (UKN),Glenn M...","Wriddhiman Saha (WK),Shubman Gill (UKN),Vijay ...","Shubman Gill,Vijay Shankar","Noor Ahmad,Rashid Khan",21 May 2023 - night match (20-over match)
1,IPL-2023,1359543,Mumbai Indians v Sunrisers Hyderabad,MI v SRH,"69th Match (D/N), Indian Premier League at Mum...",MI,SRH,MI,BOWL FIRST,200/5,...,5.0,27.0,Green century and Madhwal four-for help Mumbai...,"Cameron Green,Rohit Sharma","Akash Madhwal,Chris Jordan","Ishan Kishan (WK),Rohit Sharma (UKN),Cameron G...","Vivrant Sharma (AR),Mayank Agarwal (UKN),Heinr...","Mayank Agarwal,Vivrant Sharma","Bhuvneshwar Kumar,Mayank Dagar",21 May 2023 - day/night match (20-over match)
2,IPL-2023,1359542,Kolkata Knight Riders v Lucknow Super Giants,KKR v LSG,"68th Match (N), Indian Premier League at Kolka...",KKR,LSG,KKR,BOWL FIRST,176/8,...,8.0,22.0,"Pooran, Bishnoi seal Lucknow Super Giants' pla...","Rinku Singh,Jason Roy","Sunil Narine,Shardul Thakur","Jason Roy (UKN),Venkatesh Iyer (AR),Nitish Ran...","Karan Sharma (AR),Quinton de Kock (WK),Prerak ...","Nicholas Pooran,Quinton de Kock","Ravi Bishnoi,Yash Thakur",20 May 2023 - night match (20-over match)
3,IPL-2023,1359541,Delhi Capitals v Chennai Super Kings,DC v CSK,"67th Match (D/N), Indian Premier League at Del...",DC,CSK,CSK,BAT FIRST,223/3,...,3.0,31.0,"Gaikwad, Conway script CSK's big win. For Delh...","David Warner,Axar Patel","Chetan Sakariya,Anrich Nortje","Prithvi Shaw (UKN),David Warner (UKN),Phil Sal...","Ruturaj Gaikwad (UKN),Devon Conway (UKN),Shiva...","Devon Conway,Ruturaj Gaikwad","Deepak Chahar,Matheesha Pathirana",20 May 2023 - day/night match (20-over match)
4,IPL-2023,1359540,Punjab Kings v Rajasthan Royals,PBKS v RR,"66th Match (N), Indian Premier League at Dhara...",PBKS,RR,RR,BOWL FIRST,187/5,...,6.0,27.0,"Padikkal, Hetmyer keep Royals in the hunt with...","Sam Curran,Jitesh Sharma","Kagiso Rabada,Rahul Chahar","Prabhsimran Singh (UKN),Shikhar Dhawan (UKN),A...","Yashasvi Jaiswal (UKN),Jos Buttler (UKN),Devdu...","Devdutt Padikkal,Yashasvi Jaiswal","Navdeep Saini,Adam Zampa",19 May 2023 - night match (20-over match)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,IPL-2008,336012,Royal Challengers Bangalore v Mumbai Indians,RCB v MI,"55th match (D/N), Indian Premier League at Ben...",RCB,MI,MI,BOWL FIRST,122/9,...,1.0,16.0,Mumbai end IPL campaign with easy win. Mumbai ...,"Cameron White,Vinay Kumar","Dale Steyn,Balachandra Akhil","Mark Boucher (BT),Shreevats Goswami (WK),Misba...","Sanath Jayasuriya (AR),Sachin Tendulkar (BT),R...","Sanath Jayasuriya,Sachin Tendulkar","Dilhara Fernando,Dwayne Smith",28 May 2008 - day/night match (20-over match)
1024,IPL-2008,336019,Kings XI Punjab v Rajasthan Royals,KXIP v RR,"56th match (N), Indian Premier League at Mohal...",KXIP,RR,RR,BOWL FIRST,221/3,...,7.0,26.0,Marsh century conquers Rajasthan. Kings XI Pun...,"Shaun Marsh,James Hopes","Piyush Chawla,James Hopes","Shaun Marsh (BT),James Hopes (AR),Yuvraj Singh...","Mohammad Kaif (BT),Niraj Patel (UKN),Younis Kh...","Niraj Patel,Yusuf Pathan","Shane Watson,Yusuf Pathan",28 May 2008 - night match (20-over match)
1025,IPL-2008,336038,Delhi Daredevils v Rajasthan Royals,DC v RR,"1st Semi-Final (N), Indian Premier League at M...",DC,RR,DC,BOWL FIRST,192/9,...,9.0,29.0,Watson helps Rajasthan march into final. This ...,"Tillakaratne Dilshan,Gautam Gambhir","Farveez Maharoof,Amit Mishra","Gautam Gambhir (BT),Virender Sehwag (BT),Shikh...","Graeme Smith (BT),Swapnil Asnodkar (BT),Sohail...","Shane Watson,Yusuf Pathan","Shane Watson,Munaf Patel",30 May 2008 - night match (20-over match)
1026,IPL-2008,336039,Chennai Super Kings v Kings XI Punjab,CSK v KXIP,"2nd Semi-Final (N), Indian Premier League at M...",CSK,KXIP,KXIP,BAT FIRST,112/8,...,8.0,13.0,Inspired Chennai send Punjab packing. An inspi...,"Suresh Raina,Parthiv Patel","Manpreet Gony,Makhaya Ntini","Parthiv Patel (WK),Vidyut Sivaramakrishnan (UK...","Shaun Marsh (BT),James Hopes (AR),Kumar Sangak...","Ramesh Powar,Wilkin Mota","Irfan Pathan,Vikram Singh",31 May 2008 - night match (20-over match)
1027,IPL-2008,336040,Chennai Super Kings v Rajasthan Royals,CSK v RR,"Final (N), Indian Premier League at Mumbai, Ju...",CSK,RR,RR,BOWL FIRST,163/5,...,7.0,17.0,Rajasthan champions after cliffhanger. League ...,"Suresh Raina,Parthiv Patel","Albie Morkel,Muttiah Muralitharan","Parthiv Patel (WK),Vidyut Sivaramakrishnan (UK...","Niraj Patel (UKN),Swapnil Asnodkar (BT),Kamran...","Yusuf Pathan,Swapnil Asnodkar","Yusuf Pathan,Shane Watson",1 June 2008 - night match (20-over match)

In [21]:
df2 = pd.read_excel("excel1.xlsx", sheet_name="DATA-2")
df2

,SEASON,WINNER,RUNNER UP,PLAYER OF THE MATCH,PLAYER OF THE TOURNAMENT
0,2023,Chennai Super Kings,Gujarat Titians,Devon Conway,Shubman Gill
1,2022,Gujarat Titians,Rajasthan Royals,Hardik Pandya,Jos Butler
2,2021,Chennai Super Kings,Kolkata Knight Riders,Faf du Plessis,Harshal Patel
3,2020,Mumbai Indians,Delhi Capitals,Trent Boult,Jofra Archer
4,2019,Mumbai Indians,Chennai Super Kings,Jasprit Bumrah,Andre Russell
5,2018,Chennai Super Kings,Sunrisers Hyderabad,Shane Watson,Sunil Narine
6,2017,Mumbai Indians,Rising Pune Supergiants,Krunal Pandya,Ben Stokes
7,2016,Sunrisers Hyderabad,Royal Challengers Banglore,Ben Cutting,Virat Kohli
8,2015,Mumbai Indians,Chennai Super Kings,Rohit Sharma,Andre Russell
9,2014,Kolkata Knight Riders,Kings XI Punjab,Manish Pandey,Glenn Maxwell
10,2013,Mumbai Indians,Chennai Super Kings,Kieron Pollard,Shane Watson
11,2012,Kolkata Knight Riders,Chennai Super Kings,Manvinder Bisla,Sunil Narine
12,2011,Chennai Super Kings,Royal Challengers Banglore,Murli Vijay,Chris Gayle
13,2010,Chennai Super Kings,Mumbai Indians,Suresh Raina,Sachin Tendulkar
14,2009,Deccan Chargers,Royal Challengers Banglore,Anil Kumle,Adam Gilchrist
15,2008,Rajasthan Royals,Chennai Super Kings,Yusuf Pathan,Shane Watson

In [22]:
df2["WINNER"][0]

'Chennai Super Kings'

In [24]:
df2["WINNER"][14]

'Deccan Chargers'

In [3]:
# how to create a dataframe
# using list

id = [1,2,3,4,5]
name=["abhishek" , "karan", "krrish", "kunal", "himanshu"]
age = [24,23,24,24,23]
marks = [87,88,79,66,79]

df = pd.DataFrame({"id":id, "name":name, "age":age, "marks":marks})
print(df)

   id      name  age  marks
0   1  abhishek   24     87
1   2     karan   23     88
2   3    krrish   24     79
3   4     kunal   24     66
4   5  himanshu   23     79

In [15]:
df.to_csv("abhishek.csv", index = False)

In [16]:
df = pd.read_csv("abhishek.csv")
df

   Unnamed: 0  id      name  age  marks
0           0   1  abhishek   24     87
1           1   2     karan   23     88
2           2   3    krrish   24     79
3           3   4     kunal   24     66
4           4   5  himanshu   23     79

In [17]:
# using tuple 

id = (1,2,3,4,5)
name=("abhishek" , "karan", "krrish", "kunal", "himanshu")
age = (24,23,24,24,23)
marks = (87,88,79,66,79)

df = pd.DataFrame({"id":id, "name":name, "age":age, "marks":marks})
print(df)

   id      name  age  marks
0   1  abhishek   24     87
1   2     karan   23     88
2   3    krrish   24     79
3   4     kunal   24     66
4   5  himanshu   23     79

In [18]:
# using Series

id = pd.Series([1,2,3,4,5])
name= pd.Series(["abhishek" , "karan", "krrish", "kunal", "himanshu"])
age = pd.Series([24,23,24,24,23])
marks = pd.Series([87,88,79,66,79])

df = pd.DataFrame({"id":id, "name":name, "age":age, "marks":marks})
print(df)

   id      name  age  marks
0   1  abhishek   24     87
1   2     karan   23     88
2   3    krrish   24     79
3   4     kunal   24     66
4   5  himanshu   23     79

In [20]:
# using dictionary

id = {0:1, 1:2, 2:3, 3:4, 4:5}
name = {0:"abhishek" , 1:"karan", 2:"krrish", 3:"kunal", 4:"himanshu"}
age = {0:24, 1:23, 2:24, 3:24, 4:23}
marks =  {0:87, 1:88, 2:79, 3:66, 4:79}

df = pd.DataFrame({"id":id, "name":name, "age":age, "marks":marks})
print(df)

   id      name  age  marks
0   1  abhishek   24     87
1   2     karan   23     88
2   3    krrish   24     79
3   4     kunal   24     66
4   5  himanshu   23     79

In [3]:
# list of list

id = [1,2,3,4,5]
name = ["abhishek", "karan", "krrish", "kunal", "himanshu"]
marks = [88,76,89,87,65]
city = ["faridabad", "palwal", "ballabgarh", "hodal", "nooh"]

df = pd.DataFrame([id,name,marks,city] ,  columns = ['a','b','c','d','e'])
df

           a       b           c      d         e
0          1       2           3      4         5
1   abhishek   karan      krrish  kunal  himanshu
2         88      76          89     87        65
3  faridabad  palwal  ballabgarh  hodal      nooh

In [6]:
# df.describe() is a Pandas method that generates summary statistics for your DataFrame.

# df.describe()
df.describe(include='all')

        a  b  c  d  e
count   4  4  4  4  4
unique  4  4  4  4  4
top     1  2  3  4  5
freq    1  1  1  1  1

In [5]:
# df.info() is a Pandas method that gives a quick summary of your DataFrame. It tells you about the structure of the data, 
# not the statistical values.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       4 non-null      object
 1   b       4 non-null      object
 2   c       4 non-null      object
 3   d       4 non-null      object
 4   e       4 non-null      object
dtypes: object(5)
memory usage: 292.0+ bytes

In [12]:
data = pd.read_csv("stud (3).csv")
data

    id    name  age gender  marks  cityid  branchid
0    1    arun   25      m     78     1.0       1.0
1    2   raman   20      m     50     2.0       2.0
2    3    riya   19      f     40     2.0       3.0
3    4   pooja   27      f     90     1.0       1.0
4    5  denver   30      m     85     3.0       2.0
5    6  sachin   32      m     94     4.0       3.0
6    7   kohli   33      m     44     3.0       1.0
7    8  kavita   22      f     90     1.0       2.0
8    9   suman   20      f     80     3.0       3.0
9   10   rakhi   21      f     40     4.0       1.0
10  11   rohit   21      m     94     1.0       2.0
11  12  pankaj   25      m     55     2.0       3.0
12  13    juhi   26      f     45     2.0       1.0
13  14    john   27      m     77     4.0       2.0
14  15    anil   28      m     60     5.0       3.0
15  16    kity   29      f     70     5.0       1.0
16  17     ram   31      m     49     5.0       2.0
17  18   dhoni   28      m     60     NaN       NaN
18  19  sachin   29      f     70     NaN       NaN
19  20   rohit   31      m     49     NaN       NaN

In [13]:
pd.read_csv("stud (3).csv").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        20 non-null     int64
 1   name      20 non-null     object
 2   age       20 non-null     int64
 3   gender    20 non-null     object
 4   marks     20 non-null     int64
 5   cityid    17 non-null     float64
 6   branchid  17 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.2+ KB

In [16]:
data.head()

# By default, head() displays the first 5 rows of the DataFrame.

# Purpose
# View the beginning of the dataset.
# Check whether the data has been loaded correctly.
# Verify column names and values.

   id    name  age gender  marks  cityid  branchid
0   1    arun   25      m     78     1.0       1.0
1   2   raman   20      m     50     2.0       2.0
2   3    riya   19      f     40     2.0       3.0
3   4   pooja   27      f     90     1.0       1.0
4   5  denver   30      m     85     3.0       2.0

In [20]:
# To display the first 10 rows:

data.head(10)

   id    name  age gender  marks  cityid  branchid
0   1    arun   25      m     78     1.0       1.0
1   2   raman   20      m     50     2.0       2.0
2   3    riya   19      f     40     2.0       3.0
3   4   pooja   27      f     90     1.0       1.0
4   5  denver   30      m     85     3.0       2.0
5   6  sachin   32      m     94     4.0       3.0
6   7   kohli   33      m     44     3.0       1.0
7   8  kavita   22      f     90     1.0       2.0
8   9   suman   20      f     80     3.0       3.0
9  10   rakhi   21      f     40     4.0       1.0

In [21]:
data.head(-5)

# It returns all rows except the last 5 rows.

# | Code            | Output                     |
# | --------------- | -------------------------- |
# | `data.head()`   | First 5 rows               |
# | `data.head(10)` | First 10 rows              |
# | `data.head(-5)` | All rows except the last 5 |

    id    name  age gender  marks  cityid  branchid
0    1    arun   25      m     78     1.0       1.0
1    2   raman   20      m     50     2.0       2.0
2    3    riya   19      f     40     2.0       3.0
3    4   pooja   27      f     90     1.0       1.0
4    5  denver   30      m     85     3.0       2.0
5    6  sachin   32      m     94     4.0       3.0
6    7   kohli   33      m     44     3.0       1.0
7    8  kavita   22      f     90     1.0       2.0
8    9   suman   20      f     80     3.0       3.0
9   10   rakhi   21      f     40     4.0       1.0
10  11   rohit   21      m     94     1.0       2.0
11  12  pankaj   25      m     55     2.0       3.0
12  13    juhi   26      f     45     2.0       1.0
13  14    john   27      m     77     4.0       2.0
14  15    anil   28      m     60     5.0       3.0

In [15]:
data.tail()

# By default, tail() displays the last 5 rows of the DataFrame.

# Purpose
# View the end of the dataset.
# Check the last records.
# Verify whether data is complete.

    id    name  age gender  marks  cityid  branchid
15  16    kity   29      f     70     5.0       1.0
16  17     ram   31      m     49     5.0       2.0
17  18   dhoni   28      m     60     NaN       NaN
18  19  sachin   29      f     70     NaN       NaN
19  20   rohit   31      m     49     NaN       NaN

In [19]:
data.tail(10)

    id    name  age gender  marks  cityid  branchid
10  11   rohit   21      m     94     1.0       2.0
11  12  pankaj   25      m     55     2.0       3.0
12  13    juhi   26      f     45     2.0       1.0
13  14    john   27      m     77     4.0       2.0
14  15    anil   28      m     60     5.0       3.0
15  16    kity   29      f     70     5.0       1.0
16  17     ram   31      m     49     5.0       2.0
17  18   dhoni   28      m     60     NaN       NaN
18  19  sachin   29      f     70     NaN       NaN
19  20   rohit   31      m     49     NaN       NaN

In [22]:
data.tail(-5)

# All rows except the first 5

    id    name  age gender  marks  cityid  branchid
5    6  sachin   32      m     94     4.0       3.0
6    7   kohli   33      m     44     3.0       1.0
7    8  kavita   22      f     90     1.0       2.0
8    9   suman   20      f     80     3.0       3.0
9   10   rakhi   21      f     40     4.0       1.0
10  11   rohit   21      m     94     1.0       2.0
11  12  pankaj   25      m     55     2.0       3.0
12  13    juhi   26      f     45     2.0       1.0
13  14    john   27      m     77     4.0       2.0
14  15    anil   28      m     60     5.0       3.0
15  16    kity   29      f     70     5.0       1.0
16  17     ram   31      m     49     5.0       2.0
17  18   dhoni   28      m     60     NaN       NaN
18  19  sachin   29      f     70     NaN       NaN
19  20   rohit   31      m     49     NaN       NaN

In [23]:
data.columns

# columns returns the names of all columns in the DataFrame.

Index(['id', 'name', 'age', 'gender', 'marks', 'cityid', 'branchid'], dtype='object')

In [24]:
data.index

# index returns the row labels (indexes) of the DataFrame.

RangeIndex(start=0, stop=20, step=1)

In [25]:
data.values

# data.values returns all the data in the DataFrame as a NumPy array
# It only returns the actual values stored in the DataFrame.

array([[1, 'arun', 25, 'm', 78, 1.0, 1.0],
       [2, 'raman', 20, 'm', 50, 2.0, 2.0],
       [3, 'riya', 19, 'f', 40, 2.0, 3.0],
       [4, 'pooja', 27, 'f', 90, 1.0, 1.0],
       [5, 'denver', 30, 'm', 85, 3.0, 2.0],
       [6, 'sachin', 32, 'm', 94, 4.0, 3.0],
       [7, 'kohli', 33, 'm', 44, 3.0, 1.0],
       [8, 'kavita', 22, 'f', 90, 1.0, 2.0],
       [9, 'suman', 20, 'f', 80, 3.0, 3.0],
       [10, 'rakhi', 21, 'f', 40, 4.0, 1.0],
       [11, 'rohit', 21, 'm', 94, 1.0, 2.0],
       [12, 'pankaj', 25, 'm', 55, 2.0, 3.0],
       [13, 'juhi', 26, 'f', 45, 2.0, 1.0],
       [14, 'john', 27, 'm', 77, 4.0, 2.0],
       [15, 'anil', 28, 'm', 60, 5.0, 3.0],
       [16, 'kity', 29, 'f', 70, 5.0, 1.0],
       [17, 'ram', 31, 'm', 49, 5.0, 2.0],
       [18, 'dhoni', 28, 'm', 60, nan, nan],
       [19, 'sachin', 29, 'f', 70, nan, nan],
       [20, 'rohit', 31, 'm', 49, nan, nan]], dtype=object)

In [26]:
data.sample()

# sample() returns random row(s) from the DataFrame.
# By default, it returns 1 random row.
# sample() selects rows randomly, so the output changes each time.

    id   name  age gender  marks  cityid  branchid
17  18  dhoni   28      m     60     NaN       NaN

In [27]:
data.sample(4)

# It returns 4 random rows from the DataFrame.

    id   name  age gender  marks  cityid  branchid
19  20  rohit   31      m     49     NaN       NaN
9   10  rakhi   21      f     40     4.0       1.0
17  18  dhoni   28      m     60     NaN       NaN
1    2  raman   20      m     50     2.0       2.0

In [28]:
data.sample(frac = .10)

# The frac parameter specifies the fraction (percentage) of rows to return.
# means 10% of the total rows.

# Every time you run the code, you may get different rows because they are selected randomly.

   id    name  age gender  marks  cityid  branchid
6   7   kohli   33      m     44     3.0       1.0
7   8  kavita   22      f     90     1.0       2.0

In [29]:
data.sample(frac = 1)

# Return all rows in random order

# | Method                   | Meaning                             |
# | ------------------------ | ----------------------------------- |
# | `data.sample(n=5)`       | Return exactly **5 random rows**    |
# | `data.sample(frac=0.10)` | Return **10% of the total rows**    |
# | `data.sample(frac=1)`    | Return **all rows** in random order |

    id    name  age gender  marks  cityid  branchid
2    3    riya   19      f     40     2.0       3.0
0    1    arun   25      m     78     1.0       1.0
17  18   dhoni   28      m     60     NaN       NaN
18  19  sachin   29      f     70     NaN       NaN
7    8  kavita   22      f     90     1.0       2.0
6    7   kohli   33      m     44     3.0       1.0
1    2   raman   20      m     50     2.0       2.0
4    5  denver   30      m     85     3.0       2.0
11  12  pankaj   25      m     55     2.0       3.0
13  14    john   27      m     77     4.0       2.0
12  13    juhi   26      f     45     2.0       1.0
3    4   pooja   27      f     90     1.0       1.0
5    6  sachin   32      m     94     4.0       3.0
8    9   suman   20      f     80     3.0       3.0
10  11   rohit   21      m     94     1.0       2.0
16  17     ram   31      m     49     5.0       2.0
14  15    anil   28      m     60     5.0       3.0
9   10   rakhi   21      f     40     4.0       1.0
19  20   rohit   31      m     49     NaN       NaN
15  16    kity   29      f     70     5.0       1.0

In [30]:
# to access columns

data.name

0       arun
1      raman
2       riya
3      pooja
4     denver
5     sachin
6      kohli
7     kavita
8      suman
9      rakhi
10     rohit
11    pankaj
12      juhi
13      john
14      anil
15      kity
16       ram
17     dhoni
18    sachin
19     rohit
Name: name, dtype: object

In [31]:
data["name"]  #best

0       arun
1      raman
2       riya
3      pooja
4     denver
5     sachin
6      kohli
7     kavita
8      suman
9      rakhi
10     rohit
11    pankaj
12      juhi
13      john
14      anil
15      kity
16       ram
17     dhoni
18    sachin
19     rohit
Name: name, dtype: object

In [34]:
# access multiple columns

data[["id", "name", "marks"]]

    id    name  marks
0    1    arun     78
1    2   raman     50
2    3    riya     40
3    4   pooja     90
4    5  denver     85
5    6  sachin     94
6    7   kohli     44
7    8  kavita     90
8    9   suman     80
9   10   rakhi     40
10  11   rohit     94
11  12  pankaj     55
12  13    juhi     45
13  14    john     77
14  15    anil     60
15  16    kity     70
16  17     ram     49
17  18   dhoni     60
18  19  sachin     70
19  20   rohit     49

In [35]:
data["marks"]+2

0     80
1     52
2     42
3     92
4     87
5     96
6     46
7     92
8     82
9     42
10    96
11    57
12    47
13    79
14    62
15    72
16    51
17    62
18    72
19    51
Name: marks, dtype: int64

In [36]:
data["marks"].add(2)


# Why does Pandas have .add() if + already exists?

# Because .add() is more flexible.

# It can also add:

# another Series
# another DataFrame
# a scalar (single number)

0     80
1     52
2     42
3     92
4     87
5     96
6     46
7     92
8     82
9     42
10    96
11    57
12    47
13    79
14    62
15    72
16    51
17    62
18    72
19    51
Name: marks, dtype: int64

In [38]:
# how to add a column in dataframe 

id = [1,2,3,4,5]
name=["abhishek" , "karan", "krrish", "kunal", "himanshu"]
age = [24,23,24,24,23]
marks = [87,88,79,66,79]

df = pd.DataFrame({"id":id, "name":name, "age":age, "marks":marks})
print(df)

   id      name  age  marks
0   1  abhishek   24     87
1   2     karan   23     88
2   3    krrish   24     79
3   4     kunal   24     66
4   5  himanshu   23     79

In [39]:
df["branch"] = ["mca" , "bca" , "btech", "bba", "bsc"]

In [40]:
df

   id      name  age  marks branch
0   1  abhishek   24     87    mca
1   2     karan   23     88    bca
2   3    krrish   24     79  btech
3   4     kunal   24     66    bba
4   5  himanshu   23     79    bsc

In [44]:
df["city"] = "noida"

In [45]:
df

   id      name  age  marks branch   city
0   1  abhishek   24     87    mca  noida
1   2     karan   23     88    bca  noida
2   3    krrish   24     79  btech  noida
3   4     kunal   24     66    bba  noida
4   5  himanshu   23     79    bsc  noida

In [48]:
df["lname"] = [len(i) for i in list(df["name"])]

In [49]:
df

   id      name  age  marks branch   city  lname
0   1  abhishek   24     87    mca  noida      8
1   2     karan   23     88    bca  noida      5
2   3    krrish   24     79  btech  noida      6
3   4     kunal   24     66    bba  noida      5
4   5  himanshu   23     79    bsc  noida      8

In [58]:
# insert

id = [1,2,3,4,5]
name=["abhishek" , "karan", "krrish", "kunal", "himanshu"]
age = [24,23,24,24,23]
marks = [87,88,79,66,79]

df = pd.DataFrame({"id":id, "name":name, "age":age, "marks":marks})
print(df)

   id      name  age  marks
0   1  abhishek   24     87
1   2     karan   23     88
2   3    krrish   24     79
3   4     kunal   24     66
4   5  himanshu   23     79

In [59]:
df.insert(2, "lastName", ["morya","sharma","gulia","dixit","rajawaat"])

In [60]:
df

   id      name  lastName  age  marks
0   1  abhishek     morya   24     87
1   2     karan    sharma   23     88
2   3    krrish     gulia   24     79
3   4     kunal     dixit   24     66
4   5  himanshu  rajawaat   23     79

In [63]:
data2 = pd.read_csv("emp1 (4).csv")
data2

   eno  ename    esal       city
0   10    NaN  7500.0      noida
1   20   tina  8500.0      delhi
2   30   arun  7000.0       doon
3   40   tina     NaN     shimla
4   50  tannu  4000.0  rishikesh
5   60    NaN  2500.0      noida
6   70  nitin     NaN        NaN
7   80   arun  3500.0       doon
8   90    NaN  3000.0  rishikesh

In [64]:
data2.dropna()

# dropna() removes rows that contain missing values (NaN).

# how="any" (Default)

   eno  ename    esal       city
1   20   tina  8500.0      delhi
2   30   arun  7000.0       doon
4   50  tannu  4000.0  rishikesh
7   80   arun  3500.0       doon

In [65]:
data2.dropna(how="all")

# Remove a row only if ALL the values in that row are NaN
# If a row has at least one non-NaN value, it will not be removed

   eno  ename    esal       city
0   10    NaN  7500.0      noida
1   20   tina  8500.0      delhi
2   30   arun  7000.0       doon
3   40   tina     NaN     shimla
4   50  tannu  4000.0  rishikesh
5   60    NaN  2500.0      noida
6   70  nitin     NaN        NaN
7   80   arun  3500.0       doon
8   90    NaN  3000.0  rishikesh

In [66]:
data2.dropna(axis=1, how="all")

# This removes only those columns where every value is NaN.


# | Code                              | Meaning                                           |
# | --------------------------------- | ------------------------------------------------- |
# | `data2.dropna()`                  | Remove rows with **any** `NaN` (default behavior) |
# | `data2.dropna(how="any")`         | Same as above                                     |
# | `data2.dropna(how="all")`         | Remove rows only if **all** values are `NaN`      |
# | `data2.dropna(axis=1, how="all")` | Remove columns where all values are `NaN`         |

   eno  ename    esal       city
0   10    NaN  7500.0      noida
1   20   tina  8500.0      delhi
2   30   arun  7000.0       doon
3   40   tina     NaN     shimla
4   50  tannu  4000.0  rishikesh
5   60    NaN  2500.0      noida
6   70  nitin     NaN        NaN
7   80   arun  3500.0       doon
8   90    NaN  3000.0  rishikesh

In [67]:
data2.dropna(subset="ename")

# What does subset do?

# The subset parameter tells Pandas:

# "Check only the specified column(s) for missing values."

# Here, Pandas checks only the ename column.

# If ename contains NaN, that row is removed.
# It ignores NaN values in all other columns.

   eno  ename    esal       city
1   20   tina  8500.0      delhi
2   30   arun  7000.0       doon
3   40   tina     NaN     shimla
4   50  tannu  4000.0  rishikesh
6   70  nitin     NaN        NaN
7   80   arun  3500.0       doon

In [69]:
# Check Multiple Columns
# You can also check more than one column.

data2.dropna(subset=["ename", "city"])

   eno  ename    esal       city
1   20   tina  8500.0      delhi
2   30   arun  7000.0       doon
3   40   tina     NaN     shimla
4   50  tannu  4000.0  rishikesh
7   80   arun  3500.0       doon

In [70]:
data2.dropna(axis=0)

# Remove rows that contain missing (NaN) values.
# What does axis=0 mean?

# In Pandas:

# axis=0 → Operate on rows (default)
# axis=1 → Operate on columns

   eno  ename    esal       city
1   20   tina  8500.0      delhi
2   30   arun  7000.0       doon
4   50  tannu  4000.0  rishikesh
7   80   arun  3500.0       doon

In [72]:
data2.dropna(axis=1)

# Removes columns containing NaN

   eno
0   10
1   20
2   30
3   40
4   50
5   60
6   70
7   80
8   90

In [75]:
# now understand for loop 

id = [1,2,3,4,5]
name=["abhishek" , "karan", "krrish", "kunal", "himanshu"]
age = [24,23,24,24,23]
marks = [87,88,79,66,79]

df = pd.DataFrame({"id":id, "name":name, "age":age, "marks":marks})
print(df)

   id      name  age  marks
0   1  abhishek   24     87
1   2     karan   23     88
2   3    krrish   24     79
3   4     kunal   24     66
4   5  himanshu   23     79

In [76]:
for i in df:
    print(i)

id
name
age
marks

In [77]:
for i in df["name"]:
    print(i)

abhishek
karan
krrish
kunal
himanshu

In [78]:
df["name"][0]

'abhishek'

In [79]:
df["name"][3]

'kunal'

In [81]:
for i in df.index:
    print(df["name"][i])

abhishek
karan
krrish
kunal
himanshu

In [83]:
data = pd.read_csv("stud (3).csv")
data

    id    name  age gender  marks  cityid  branchid
0    1    arun   25      m     78     1.0       1.0
1    2   raman   20      m     50     2.0       2.0
2    3    riya   19      f     40     2.0       3.0
3    4   pooja   27      f     90     1.0       1.0
4    5  denver   30      m     85     3.0       2.0
5    6  sachin   32      m     94     4.0       3.0
6    7   kohli   33      m     44     3.0       1.0
7    8  kavita   22      f     90     1.0       2.0
8    9   suman   20      f     80     3.0       3.0
9   10   rakhi   21      f     40     4.0       1.0
10  11   rohit   21      m     94     1.0       2.0
11  12  pankaj   25      m     55     2.0       3.0
12  13    juhi   26      f     45     2.0       1.0
13  14    john   27      m     77     4.0       2.0
14  15    anil   28      m     60     5.0       3.0
15  16    kity   29      f     70     5.0       1.0
16  17     ram   31      m     49     5.0       2.0
17  18   dhoni   28      m     60     NaN       NaN
18  19  sachin   29      f     70     NaN       NaN
19  20   rohit   31      m     49     NaN       NaN

In [86]:
male = 0
female = 0 

for i in data["gender"]:
    if i == "m":
        male=male+1
    else:
        female = female+1

print("Male:",  male)
print("Female:" , female)

Male: 12
Female: 8

In [87]:
data = pd.read_csv("st.csv")
data

     id     name  age gender  marks branch
0     1      Ram   24      m     95  civil
1     2    Shyam   23      m     80    eee
2     3     Sita   20      f     85     cs
3     4    Geeta   21      f     93    eee
4     5    Kamal   18      m     77     me
..  ...      ...  ...    ...    ...    ...
95   96    Sneha   32      f     59    eee
96   97    Sumit   34      m     50  civil
97   98  Aarunya   21      f     88  civil
98   99  Atharva   20      m     90     me
99  100    Kowid   21      m     92  civil

[100 rows x 6 columns]

In [91]:
data["branch"].value_counts()

branch
cs       22
civil    21
eee      16
it       16
me       14
ec       11
Name: count, dtype: int64

In [94]:
d = {}

for i in data["branch"]:
    if i in d:
        d[i] += 1
    else:
        d[i] = 1

print(d)

{'civil': 21, 'eee': 16, 'cs': 22, 'me': 14, 'ec': 11, 'it': 16}

In [96]:
data1 = pd.read_csv("user (2).csv")
data1

      us  pwd
0    ram  123
1   arun  111
2   tina  333
3  ankit  121
4   riya  345

In [109]:
username = input("Enter your username: ")
password = input("Enter your password: ")

found = False

for i in range(len(data1)):
    if username == data1["us"][i] and password == str(data1["pwd"][i]):
        found = True
        break

if found:
    print("Valid Credentials")
else:
    print("Invalid Credentials")

Enter your username:  riya
Enter your password:  345

Valid Credentials

In [113]:
data.sort_values(by="age", ascending = False)

    id        name  age gender  marks branch
65  66    Mahender   35      m     77    eee
6    7        Shiv   35      m     80     ec
39  40     Devvrat   35      m     80     me
13  14        Ravi   35      m     51     cs
52  53    Anukampa   35      f     95     cs
..  ..         ...  ...    ...    ...    ...
54  55   Parikshit   18      m     90  civil
74  75     Shubham   18      m     85     cs
4    5       Kamal   18      m     77     me
57  58     Aarunya   18      f     98     it
53  54  Pratishtha   18      f     94     it

[100 rows x 6 columns]

In [115]:
data.sort_index(ascending=False)

     id     name  age gender  marks branch
99  100    Kowid   21      m     92  civil
98   99  Atharva   20      m     90     me
97   98  Aarunya   21      f     88  civil
96   97    Sumit   34      m     50  civil
95   96    Sneha   32      f     59    eee
..  ...      ...  ...    ...    ...    ...
4     5    Kamal   18      m     77     me
3     4    Geeta   21      f     93    eee
2     3     Sita   20      f     85     cs
1     2    Shyam   23      m     80    eee
0     1      Ram   24      m     95  civil

[100 rows x 6 columns]