In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('smartphone.csv')

In [93]:
df.head(6)

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
5,Samsung Galaxy F23 5G (6GB RAM + 128GB),"₹16,999",80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 750G, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.6 inches, 1080 x 2408 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 1 TB",Android v12

## Data Assessing

### Quality Issues

1. **model** - some brands are written diiferently like OPPO in model column `consistency`
2. **price** - has unneccesary '₹' `validity`
3. **price** - has ',' between numbers `validity`
4. **price** - phone Namotel has a price of 99 `accuracy`
5. **ratings** - missing values `completeness`
6. **processor** - has some incorrect values for some samsung phones(row # -642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002) `validity`
7. There is ipod on row 756 `validity`
8. **memory** - incorrect values in rows (441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002) `validity`
9. **battery** - incorrect values in rows(113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002) `validity`
10. **display** - sometimes frequency is not available `completeness`
11. **display** - incorrect values in rows(378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002) `validity`
12. certain phones are foldable and the info is scattered `validity`
13. **camera** - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
14. **camera** - problem with rows (100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016
) `validity`
15. **card** - sometimes contains info about os and camera `validity`
16. **os** - sometimes contains info about bluetooth and fm radio `validity`
17. **os** - issue with rows (324,378) `validity`
18. **os** - sometimes contains os version name like lollipop `consistency`
19. missing values in camera, card and os `completeness`
20. datatype  of price and rating is incorrect `validity`



### Tidiness Issues

1. **sim** - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
2. **ram** - can be split into 2 cols RAM and ROM
3. **processor** - can be split into processor name, cores and cpu speed.
4. **battery** - can be split into battery capacity, fast_charging_available
5. **display** - can be split into size, resolution_width, resolution_height and frequency
6. **camera** - can be split into front and rear camera
7. **card** - can be split into supported, extended_upto

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   object
 1   price      1020 non-null   object
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object
 4   processor  1020 non-null   object
 5   ram        1020 non-null   object
 6   battery    1020 non-null   object
 7   display    1020 non-null   object
 8   camera     1019 non-null   object
 9   card       1013 non-null   object
 10  os         1003 non-null   object
dtypes: float64(1), object(10)
memory usage: 87.8+ KB

In [5]:
df.describe()

           rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [6]:
df.duplicated().sum()

0

In [7]:
# make a copy
df1 = df.copy()

In [8]:
df1['price'] = df1['price'].str.replace('₹','').str.replace(',','').astype('int')

In [9]:
df1

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...
1015,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [10]:
df1 = df1.reset_index()
df1['index'] = df1['index'] + 2

In [11]:
df1['index'] = df1['index'] + 2

In [12]:
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,4,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,5,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,6,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,7,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,8,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1019,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1020,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1021,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1022,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1023,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [13]:
processor_rows = set((642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002))
ram_rows = set((441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002))
battery_rows = set((113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002))
display_rows = set((378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002))
camera_rows = set((100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016 ))

In [14]:
df1[df1['index'].isin(processor_rows | ram_rows | battery_rows | display_rows | camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
96,100,OPPO A17,12499,72.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with Fast Charging,"6.56 inches, 720 x 1612 px Display with Water ...",50 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
109,113,OnePlus 10R 5G (12GB RAM + 256GB),36999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
147,151,Samsung Galaxy M34 5G,16999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Exynos 1200, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 25W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP Quad Rear & 32 MP Front Camera,Memory Card (Hybrid),Android v12
153,157,Oppo A98,30990,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
157,161,OPPO F21 Pro 5G,25969,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.43 inches, 1080 x 2400 px Display with Punch...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12
...,...,...,...,...,...,...,...,...,...,...,...,...
952,956,iQOO Z8 5G,14999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695 , Octa Core, 2.2 GHz Processor","4 GB RAM, 128 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.58 inches, 1080 x 2412 px, 120 Hz Display wi...",50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
986,990,Vivo Y21 (2020),9990,65.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 450, Octa Core, 1.8 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.5 inches, 720 x 1544 px Display with Water D...",13 MP + 2 MP Dual Rear & 13 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
991,995,Samsung Galaxy A11,9990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Octa Core, 1.8 GHz Processor","2 GB RAM, 32 GB inbuilt",4000 mAh Battery with 15W Fast Charging,"6.4 inches, 720 x 1560 px Display with Punch Hole",13 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 512 GB",Android v10
998,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v12
1012,1016,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor","2 GB RAM, 32 GB inbuilt",3020 mAh Battery,"5 inches, 854 x 480 px Display",2 MP Rear Camera,Android v11,No FM Radio

In [15]:
df1[df1['index'].isin(processor_rows & ram_rows & battery_rows & display_rows & camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
638,642,Tecno Camon 19 Pro,17990,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G96, Octa Core, 2.05 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.8 inches, 1080 x 2460 px, 120 Hz Display wit...",64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,Bluetooth
643,647,Xiaomi 11T Pro 5G (12GB RAM + 256GB),38999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
645,649,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
655,659,Xiaomi Redmi 9,8999,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v10
663,667,Infinix Hot 12 Pro,10850,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T616, Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,"Memory Card Supported, upto 256 GB",Android v12
746,750,Xiaomi Mi 10T Pro 5G,29999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 865 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 13 MP + 5 MP Triple Rear & 20 MP Fron...,Android v10,No FM Radio
755,759,Xiaomi Poco F1 (6GB RAM + 128GB),12999,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 845, Octa Core, 2.8 GHz Processor","6 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.18 inches, 1080 x 2246 px Display with Large...",12 MP + 5 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v8.1 (Oreo)
815,819,Xiaomi Redmi 13 Prime 5G,17990,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5100 mAh Battery with 18W Fast Charging,"6.73 inches, 1080 x 2408 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v13
880,884,Tecno Pova Neo 2,13990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G85, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",7000 mAh Battery,"6.82 inches, 720 x 1600 px, 90 Hz Display with...",16 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
923,927,Realme A1,8999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","2 GB RAM, 16 GB inbuilt",4000 mAh Battery,"6.2 inches, 720 x 1520 px Display with Water D...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
925,929,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
928,932,Apple iPhone 15 Plus,84990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Bionic A16, Hexa Core Processor","8 GB RAM, 128 GB inbuilt",4532 mAh Battery with Fast Charging,"6.71 inches, 1284 x 2778 px, 120 Hz Display wi...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16
998,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v12

In [16]:
df1 = df1[df1['price'] >= 3400]

In [17]:
df1.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,4,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,5,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,6,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,7,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,8,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [18]:
df1[df1['index'].isin(processor_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
638,642,Tecno Camon 19 Pro,17990,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G96, Octa Core, 2.05 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.8 inches, 1080 x 2460 px, 120 Hz Display wit...",64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,Bluetooth
643,647,Xiaomi 11T Pro 5G (12GB RAM + 256GB),38999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
645,649,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
655,659,Xiaomi Redmi 9,8999,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v10
663,667,Infinix Hot 12 Pro,10850,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T616, Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,"Memory Card Supported, upto 256 GB",Android v12
697,701,Infinix Smart 6 Plus,8299,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G25, Octa Core, 2 GHz Processor","3 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.82 inches, 720 x 1600 px Display with Water ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
746,750,Xiaomi Mi 10T Pro 5G,29999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 865 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 13 MP + 5 MP Triple Rear & 20 MP Fron...,Android v10,No FM Radio
755,759,Xiaomi Poco F1 (6GB RAM + 128GB),12999,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 845, Octa Core, 2.8 GHz Processor","6 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.18 inches, 1080 x 2246 px Display with Large...",12 MP + 5 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v8.1 (Oreo)
815,819,Xiaomi Redmi 13 Prime 5G,17990,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5100 mAh Battery with 18W Fast Charging,"6.73 inches, 1080 x 2408 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v13
855,859,Realme 6 (6GB RAM + 64GB),12989,77.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G90T , Octa Core, 2.05 GHz Processor","6 GB RAM, 64 GB inbuilt",4300 mAh Battery with 30W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP Quad Rear & 16 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
879,883,Nokia X30,41990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 13 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
880,884,Tecno Pova Neo 2,13990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G85, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",7000 mAh Battery,"6.82 inches, 720 x 1600 px, 90 Hz Display with...",16 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
915,919,OPPO A15,9999,66.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P35, Octa Core, 2.3 GHz Processor","3 GB RAM, 32 GB inbuilt",4230 mAh Battery,"6.52 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP + 2 MP Triple Rear & 5 MP Front C...,"Memory Card Supported, upto 256 GB",Android v10.0
923,927,Realme A1,8999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","2 GB RAM, 16 GB inbuilt",4000 mAh Battery,"6.2 inches, 720 x 1520 px Display with Water D...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
925,929,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
928,932,Apple iPhone 15 Plus,84990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Bionic A16, Hexa Core Processor","8 GB RAM, 128 GB inbuilt",4532 mAh Battery with Fast Charging,"6.71 inches, 1284 x 2778 px, 120 Hz Display wi...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16
998,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v12

In [19]:
df1.drop([645,857,882,925],inplace=True)

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\1676279141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([645,857,882,925],inplace=True)

In [20]:
df1[df1['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
437,441,Motorola Moto E32,8999,71.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G37, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.5 inches, 720 x 1600 px, 90 Hz Display with ...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
481,485,Itel A24 Pro,5990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Unisoc SC9832E, Quad Core, 1.4 GHz Processor","2 GB RAM, 32 GB inbuilt",3020 mAh Battery,"5 inches, 854 x 480 px Display",2 MP Rear & 0.3 MP Front Camera,Memory Card Supported,Android v12
530,534,Vivo V20,23269,85.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 720G , Octa Core, 2.3 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 33W Fast Charging,"6.44 inches, 1080 x 2400 px Display with Water...",64 MP + 8 MP + 2 MP Triple Rear & 44 MP Front ...,"Memory Card Supported, upto 1 TB",Android v11
549,553,Realme 8s 5G,17999,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 810 5G, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB",Android v11
580,584,Nokia G60,28498,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",4500 mAh Battery with 20W Fast Charging,"6.58 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,Memory Card (Hybrid),Android v12
606,610,Apple iPhone 11 Pro Max,109900,77.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","A13 Bionic, Hexa Core, 2.65 GHz Processor","4 GB RAM, 64 GB inbuilt",3500 mAh Battery with 18W Fast Charging,"6.5 inches, 1242 x 2688 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v13
609,613,Sony Xperia Ace IV,19990,80.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v13
638,642,Tecno Camon 19 Pro,17990,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G96, Octa Core, 2.05 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.8 inches, 1080 x 2460 px, 120 Hz Display wit...",64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,Bluetooth
643,647,Xiaomi 11T Pro 5G (12GB RAM + 256GB),38999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
655,659,Xiaomi Redmi 9,8999,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v10
663,667,Infinix Hot 12 Pro,10850,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T616, Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,"Memory Card Supported, upto 256 GB",Android v12
697,701,Infinix Smart 6 Plus,8299,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G25, Octa Core, 2 GHz Processor","3 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.82 inches, 720 x 1600 px Display with Water ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
746,750,Xiaomi Mi 10T Pro 5G,29999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 865 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 13 MP + 5 MP Triple Rear & 20 MP Fron...,Android v10,No FM Radio
755,759,Xiaomi Poco F1 (6GB RAM + 128GB),12999,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 845, Octa Core, 2.8 GHz Processor","6 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.18 inches, 1080 x 2246 px Display with Large...",12 MP + 5 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v8.1 (Oreo)
815,819,Xiaomi Redmi 13 Prime 5G,17990,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5100 mAh Battery with 18W Fast Charging,"6.73 inches, 1080 x 2408 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v13
855,859,Realme 6 (6GB RAM + 64GB),12989,77.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G90T , Octa Core, 2.05 GHz Processor","6 GB RAM, 64 GB inbuilt",4300 mAh Battery with 30W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP Quad Rear & 16 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
880,884,Tecno Pova Neo 2,13990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G85, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",7000 mAh Battery,"6.82 inches, 720 x 1600 px, 90 Hz Display with...",16 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
915,919,OPPO A15,9999,66.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P35, Octa Core, 2.3 GHz Processor","3 GB RAM, 32 GB inbuilt",4230 mAh Battery,"6.52 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP + 2 MP Triple Rear & 5 MP Front C...,"Memory Card Supported, upto 256 GB",Android v10.0
923,927,Realme A1,8999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","2 GB RAM, 16 GB inbuilt",4000 mAh Battery,"6.2 inches, 720 x 1520 px Display with Water D...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
928,932,Apple iPhone 15 Plus,84990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Bionic A16, Hexa Core Processor","8 GB RAM, 128 GB inbuilt",4532 mAh Battery with Fast Charging,"6.71 inches, 1284 x 2778 px, 120 Hz Display wi...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16
986,990,Vivo Y21 (2020),9990,65.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 450, Octa Core, 1.8 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.5 inches, 720 x 1544 px Display with Water D...",13 MP + 2 MP Dual Rear & 13 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
998,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v12

In [21]:
df1.drop(582,inplace=True)

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\544825702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(582,inplace=True)

In [22]:
df1[df1['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
109,113,OnePlus 10R 5G (12GB RAM + 256GB),36999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
147,151,Samsung Galaxy M34 5G,16999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Exynos 1200, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 25W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP Quad Rear & 32 MP Front Camera,Memory Card (Hybrid),Android v12
305,309,Xiaomi Mi 11 Lite NE 5G,21890,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 778G , Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",4250 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 90 Hz Display wit...",64 MP + 8 MP + 5 MP Triple Rear & 20 MP Front ...,Memory Card (Hybrid),Android v11
361,365,Xiaomi 12T Pro 5G,59990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",200 MP + 8 MP + 2 MP Triple Rear & 20 MP Front...,Android v12,No FM Radio
374,378,Google Pixel 4,20120,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","Snapdragon 855, Octa Core, 2.8 GHz Processor","6 GB RAM, 64 GB inbuilt",2800 mAh Battery with Fast Charging,"5.7 inches, 1080 x 2280 px Display",16 MP + 12.2 MP Dual Rear & 8 MP + TOF 3D Dual...,Memory Card Not Supported,Android v10
437,441,Motorola Moto E32,8999,71.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G37, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.5 inches, 720 x 1600 px, 90 Hz Display with ...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
446,450,Xiaomi Redmi Note 12 Pro Plus (6GB RAM + 128GB),26999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",4980 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",200 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v12
549,553,Realme 8s 5G,17999,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 810 5G, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB",Android v11
580,584,Nokia G60,28498,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",4500 mAh Battery with 20W Fast Charging,"6.58 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,Memory Card (Hybrid),Android v12
606,610,Apple iPhone 11 Pro Max,109900,77.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","A13 Bionic, Hexa Core, 2.65 GHz Processor","4 GB RAM, 64 GB inbuilt",3500 mAh Battery with 18W Fast Charging,"6.5 inches, 1242 x 2688 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v13
609,613,Sony Xperia Ace IV,19990,80.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v13
626,630,Vivo V21 5G,23994,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 800U, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 33W Fast Charging,"6.44 inches, 1080 x 2400 px, 90 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 44 MP Front ...,Memory Card (Hybrid),Android v11
638,642,Tecno Camon 19 Pro,17990,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G96, Octa Core, 2.05 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.8 inches, 1080 x 2460 px, 120 Hz Display wit...",64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,Bluetooth
643,647,Xiaomi 11T Pro 5G (12GB RAM + 256GB),38999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
655,659,Xiaomi Redmi 9,8999,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v10
663,667,Infinix Hot 12 Pro,10850,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T616, Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,"Memory Card Supported, upto 256 GB",Android v12
697,701,Infinix Smart 6 Plus,8299,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G25, Octa Core, 2 GHz Processor","3 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.82 inches, 720 x 1600 px Display with Water ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
746,750,Xiaomi Mi 10T Pro 5G,29999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 865 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 13 MP + 5 MP Triple Rear & 20 MP Fron...,Android v10,No FM Radio
752,756,Realme XT,13279,75.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 712, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",4000 mAh Battery with 20W Fast Charging,"6.4 inches, 1080 x 2340 px Display with Water ...",64 MP Quad Rear & 16 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v9.0 (Pie)
755,759,Xiaomi Poco F1 (6GB RAM + 128GB),12999,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 845, Octa Core, 2.8 GHz Processor","6 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.18 inches, 1080 x 2246 px Display with Large...",12 MP + 5 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v8.1 (Oreo)
760,764,Vivo S17 Pro,49990,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9200, Octa Core Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v13,No FM Radio
815,819,Xiaomi Redmi 13 Prime 5G,17990,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5100 mAh Battery with 18W Fast Charging,"6.73 inches, 1080 x 2408 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v13
851,855,Realme Q2i,9999,69.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 720, Octa Core, 2 GHz Processor","4 GB RAM, 128 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",13 MP + 2 MP + 2 MP Triple Rear & 8 MP Front C...,Android v10,No FM Radio
855,859,Realme 6 (6GB RAM + 64GB),12989,77.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G90T , Octa Core, 2.05 GHz Processor","6 GB RAM, 64 GB inbuilt",4300 mAh Battery with 30W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP Quad Rear & 16 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
880,884,Tecno Pova Neo 2,13990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G85, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",7000 mAh Battery,"6.82 inches, 720 x 1600 px, 90 Hz Display with...",16 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v12
911,915,Samsung Galaxy M12,10999,72.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Exynos 850, Octa Core, 2 GHz Processor","4 GB RAM, 64 GB inbuilt",6000 mAh Battery with 15W Fast Charging,"6.5 inches, 720 x 1600 px, 90 Hz Display with ...",48 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v11
912,916,OnePlus Nord N100,16990,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 460, Octa Core, 1.8 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.52 inches, 720 x 1600 px, 90 Hz Display with...",13 MP + 2 MP + 2 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 256 GB",Android v10
923,927,Realme A1,8999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","2 GB RAM, 16 GB inbuilt",4000 mAh Battery,"6.2 inches, 720 x 1520 px Display with Water D...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
928,932,Apple iPhone 15 Plus,84990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Bionic A16, Hexa Core Processor","8 GB RAM, 128 GB inbuilt",4532 mAh Battery with Fast Charging,"6.71 inches, 1284 x 2778 px, 120 Hz Display wi...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16
986,990,Vivo Y21 (2020),9990,65.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 450, Octa Core, 1.8 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.5 inches, 720 x 1544 px Display with Water D...",13 MP + 2 MP Dual Rear & 13 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v10
998,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported,Android v12

In [23]:
df1.drop([376,754],inplace=True)

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\2579486625.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([376,754],inplace=True)

In [24]:
temp_df = df1[df1['index'].isin(battery_rows)]

In [25]:
x = temp_df.iloc[:,7:].shift(1,axis=1).values

In [26]:
df1.loc[temp_df.index,temp_df.columns[7:]] = x

In [27]:
df1[df1['index'].isin(display_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
374,378,Google Pixel 4,20120,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","Snapdragon 855, Octa Core, 2.8 GHz Processor","6 GB RAM, 64 GB inbuilt",None,2800 mAh Battery with Fast Charging,"5.7 inches, 1080 x 2280 px Display",16 MP + 12.2 MP Dual Rear & 8 MP + TOF 3D Dual...,Memory Card Not Supported
437,441,Motorola Moto E32,8999,71.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G37, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",None,5000 mAh Battery with 10W Fast Charging,"6.5 inches, 720 x 1600 px, 90 Hz Display with ...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB"
446,450,Xiaomi Redmi Note 12 Pro Plus (6GB RAM + 128GB),26999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",None,4980 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",200 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported
549,553,Realme 8s 5G,17999,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 810 5G, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",None,5000 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB"
580,584,Nokia G60,28498,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",None,4500 mAh Battery with 20W Fast Charging,"6.58 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,Memory Card (Hybrid)
606,610,Apple iPhone 11 Pro Max,109900,77.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","A13 Bionic, Hexa Core, 2.65 GHz Processor","4 GB RAM, 64 GB inbuilt",None,3500 mAh Battery with 18W Fast Charging,"6.5 inches, 1242 x 2688 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported
609,613,Sony Xperia Ace IV,19990,80.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","8 GB RAM, 128 GB inbuilt",None,5000 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 1 TB"
626,630,Vivo V21 5G,23994,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 800U, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",None,4000 mAh Battery with 33W Fast Charging,"6.44 inches, 1080 x 2400 px, 90 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 44 MP Front ...,Memory Card (Hybrid)
638,642,Tecno Camon 19 Pro,17990,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G96, Octa Core, 2.05 GHz Processor","8 GB RAM, 128 GB inbuilt",None,5000 mAh Battery with 33W Fast Charging,"6.8 inches, 1080 x 2460 px, 120 Hz Display wit...",64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12
643,647,Xiaomi 11T Pro 5G (12GB RAM + 256GB),38999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",None,5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11
655,659,Xiaomi Redmi 9,8999,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",None,5000 mAh Battery,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB"
663,667,Infinix Hot 12 Pro,10850,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T616, Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",None,5000 mAh Battery with 18W Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",50 MP + Depth Sensor Dual Rear & 8 MP Front Ca...,"Memory Card Supported, upto 256 GB"
697,701,Infinix Smart 6 Plus,8299,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G25, Octa Core, 2 GHz Processor","3 GB RAM, 64 GB inbuilt",None,5000 mAh Battery,"6.82 inches, 720 x 1600 px Display with Water ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB"
746,750,Xiaomi Mi 10T Pro 5G,29999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 865 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",None,5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 13 MP + 5 MP Triple Rear & 20 MP Fron...,Android v10
755,759,Xiaomi Poco F1 (6GB RAM + 128GB),12999,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 845, Octa Core, 2.8 GHz Processor","6 GB RAM, 128 GB inbuilt",None,4000 mAh Battery with Fast Charging,"6.18 inches, 1080 x 2246 px Display with Large...",12 MP + 5 MP Dual Rear & 20 MP Front Camera,"Memory Card (Hybrid), upto 256 GB"
760,764,Vivo S17 Pro,49990,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9200, Octa Core Processor","12 GB RAM, 256 GB inbuilt",None,5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v13
815,819,Xiaomi Redmi 13 Prime 5G,17990,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",None,5100 mAh Battery with 18W Fast Charging,"6.73 inches, 1080 x 2408 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB"
855,859,Realme 6 (6GB RAM + 64GB),12989,77.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G90T , Octa Core, 2.05 GHz Processor","6 GB RAM, 64 GB inbuilt",None,4300 mAh Battery with 30W Fast Charging,"6.5 inches, 1080 x 2400 px, 90 Hz Display with...",64 MP Quad Rear & 16 MP Front Camera,"Memory Card Supported, upto 256 GB"
880,884,Tecno Pova Neo 2,13990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G85, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",None,7000 mAh Battery,"6.82 inches, 720 x 1600 px, 90 Hz Display with...",16 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 512 GB"
911,915,Samsung Galaxy M12,10999,72.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Exynos 850, Octa Core, 2 GHz Processor","4 GB RAM, 64 GB inbuilt",None,6000 mAh Battery with 15W Fast Charging,"6.5 inches, 720 x 1600 px, 90 Hz Display with ...",48 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB"
912,916,OnePlus Nord N100,16990,68.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 460, Octa Core, 1.8 GHz Processor","4 GB RAM, 64 GB inbuilt",None,5000 mAh Battery with 18W Fast Charging,"6.52 inches, 720 x 1600 px, 90 Hz Display with...",13 MP + 2 MP + 2 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 256 GB"
923,927,Realme A1,8999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","2 GB RAM, 16 GB inbuilt",None,4000 mAh Battery,"6.2 inches, 720 x 1520 px Display with Water D...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB"
928,932,Apple iPhone 15 Plus,84990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Bionic A16, Hexa Core Processor","8 GB RAM, 128 GB inbuilt",None,4532 mAh Battery with Fast Charging,"6.71 inches, 1284 x 2778 px, 120 Hz Display wi...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported
986,990,Vivo Y21 (2020),9990,65.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 450, Octa Core, 1.8 GHz Processor","4 GB RAM, 64 GB inbuilt",None,5000 mAh Battery,"6.5 inches, 720 x 1544 px Display with Water D...",13 MP + 2 MP Dual Rear & 13 MP Front Camera,"Memory Card Supported, upto 256 GB"
998,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",None,5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported

In [28]:
len(display_rows)

27

In [29]:
len(camera_rows)

64

In [30]:
df1[df1['index'].isin(camera_rows)]
# 155 271

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
96,100,OPPO A17,12499,72.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with Fast Charging,"6.56 inches, 720 x 1612 px Display with Water ...",50 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
109,113,OnePlus 10R 5G (12GB RAM + 256GB),36999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",None,5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12
147,151,Samsung Galaxy M34 5G,16999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Exynos 1200, Octa Core, 2.4 GHz Processor","6 GB RAM, 128 GB inbuilt",None,6000 mAh Battery with 25W Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP Quad Rear & 32 MP Front Camera,Memory Card (Hybrid)
153,157,Oppo A98,30990,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12
157,161,OPPO F21 Pro 5G,25969,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.43 inches, 1080 x 2400 px Display with Punch...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12
...,...,...,...,...,...,...,...,...,...,...,...,...
952,956,iQOO Z8 5G,14999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695 , Octa Core, 2.2 GHz Processor","4 GB RAM, 128 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.58 inches, 1080 x 2412 px, 120 Hz Display wi...",50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
986,990,Vivo Y21 (2020),9990,65.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 450, Octa Core, 1.8 GHz Processor","4 GB RAM, 64 GB inbuilt",None,5000 mAh Battery,"6.5 inches, 720 x 1544 px Display with Water D...",13 MP + 2 MP Dual Rear & 13 MP Front Camera,"Memory Card Supported, upto 256 GB"
991,995,Samsung Galaxy A11,9990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Octa Core, 1.8 GHz Processor","2 GB RAM, 32 GB inbuilt",4000 mAh Battery with 15W Fast Charging,"6.4 inches, 720 x 1560 px Display with Punch Hole",13 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 512 GB",Android v10
998,1002,Blackview BV5200 Pro,8990,67.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Helio G35, Octa Core, 2.3 GHz Processor","4 GB RAM, 64 GB inbuilt",None,5180 mAh Battery with 10W Fast Charging,"6.1 inches, 720 x 1560 px Display with Punch Hole",13 MP Dual Rear & 8 MP Front Camera,Memory Card Supported
1012,1016,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor","2 GB RAM, 32 GB inbuilt",3020 mAh Battery,"5 inches, 854 x 480 px Display",2 MP Rear Camera,Android v11,No FM Radio

In [31]:
df1.drop([155, 271],inplace=True)

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\1013040976.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([155, 271],inplace=True)

In [32]:
temp_df = df1[df1['index'].isin(camera_rows)]

In [33]:
temp_df = temp_df[~temp_df['camera'].str.contains('MP')]

In [34]:
df1.loc[temp_df.index, 'camera'] = temp_df['card'].values

In [35]:
df1['card'].value_counts()

card
Memory Card Supported, upto 1 TB                          167
Memory Card Not Supported                                 108
Android v12                                               104
Memory Card Supported, upto 512 GB                        102
Memory Card (Hybrid), upto 1 TB                            90
                                                         ...
64 MP + 8 MP + 2 MP Triple Rear & 44 MP Front Camera        1
Android v10.0                                               1
64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front Camera       1
108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front Camera       1
50 MP + 50 MP + 10 MP Triple Rear & 32 MP Front Camera      1
Name: count, Length: 81, dtype: int64

In [36]:
temp_df = df1[df1['card'].str.contains('MP')]

In [37]:
df1.loc[temp_df.index,'card'] = 'Memory Card Not Supported'

In [38]:
df1['card'].value_counts()

card
Memory Card Supported, upto 1 TB       167
Memory Card Not Supported              165
Android v12                            104
Memory Card Supported, upto 512 GB     102
Memory Card (Hybrid), upto 1 TB         90
Memory Card Supported                   88
Memory Card Supported, upto 256 GB      81
Android v13                             45
Android v11                             40
Memory Card (Hybrid)                    26
Memory Card (Hybrid), upto 256 GB       12
Memory Card (Hybrid), upto 512 GB       11
Android v10                              9
Memory Card Supported, upto 128 GB       6
iOS v14                                  6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 64 GB         3
Memory Card (Hybrid), upto 128 GB        3
Android v9.0 (Pie)                       2
iOS v15                                  2
iOS v14.0                                2
Android v12.1                            1
Memory Card Supported, upto 1000 GB      1
iOS v10                                  1
Android v10.0                            1
iOS v13                                  1
HarmonyOS v2.0                           1
iOS v16                                  1
Memory Card (Hybrid), upto 2 TB          1
HarmonyOS                                1
Name: count, dtype: int64

In [39]:
pd.set_option('display.max_rows', None)

In [40]:
temp_df = df1[~df1['card'].str.contains('Memory Card')]

In [41]:
df1.loc[temp_df.index,'os'] = temp_df['card'].values

In [42]:
df1.loc[temp_df.index,'card'] = 'Memory Card Not Supported'

In [43]:
df1['card'].value_counts()

card
Memory Card Not Supported              382
Memory Card Supported, upto 1 TB       167
Memory Card Supported, upto 512 GB     102
Memory Card (Hybrid), upto 1 TB         90
Memory Card Supported                   88
Memory Card Supported, upto 256 GB      81
Memory Card (Hybrid)                    26
Memory Card (Hybrid), upto 256 GB       12
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card Supported, upto 1000 GB      1
Memory Card (Hybrid), upto 2 TB          1
Name: count, dtype: int64

In [44]:
df1['os'].value_counts()

os
Android v12                           386
Android v11                           270
Android v13                            89
Android v10                            64
Android v9.0 (Pie)                     28
Android v10.0                          23
iOS v16                                14
iOS v15                                12
Memory Card Not Supported              10
Android v8.1 (Oreo)                     8
Memory Card Supported, upto 256 GB      8
iOS v14                                 6
Memory Card (Hybrid)                    5
Android v11.0                           4
Android v8.0 (Oreo)                     4
Memory Card Supported, upto 1 TB        4
iOS v15.0                               3
Memory Card Supported, upto 512 GB      3
Memory Card (Hybrid), upto 256 GB       3
iOS v13                                 3
Android v5.1.1 (Lollipop)               2
HarmonyOS v2.0                          2
Memory Card (Hybrid), upto 2 TB         2
Android v6.0 (Marshmallow)              2
Android v12.1                           2
EMUI v12                                2
Harmony v2.0                            2
iOS v14.0                               2
Memory Card Supported, upto 128 GB      1
HarmonyOS                               1
Android v7.1 (Nougat)                   1
Android                                 1
Hongmeng OS v4.0                        1
Android v9 (Pie)                        1
Android v5.1 (Lollipop)                 1
RTOS (Series 30+)                       1
Memory Card (Hybrid), upto 1 TB         1
iOS v10                                 1
Pragati OS (Powered by Android)         1
Bluetooth                               1
Hongmeng OS v3.0                        1
Android v4.4.2 (KitKat)                 1
iOS v17                                 1
iOS v12.3                               1
iOS v13.0                               1
HarmonyOS v2                            1
Memory Card Supported                   1
Name: count, dtype: int64

In [45]:
temp_df = df1[df1['os'] == 'Bluetooth']

In [46]:
df1.loc[temp_df.index,'os'] = np.nan

In [47]:
df1.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,4,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,5,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,6,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,7,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,8,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [48]:
df1['display'].value_counts()

display
6.67 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          51
6.5 inches, 720 x 1600 px Display with Water Drop Notch              35
6.7 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           24
6.52 inches, 720 x 1600 px Display with Water Drop Notch             23
6.51 inches, 720 x 1600 px Display with Water Drop Notch             21
6.5 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            20
6.43 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole           19
6.43 inches, 1080 x 2400 px Display with Punch Hole                  16
6.62 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          15
6.4 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            14
6.53 inches, 720 x 1600 px Display with Water Drop Notch             13
6.55 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          11
6.7 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           10
6.6 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            10
6.7 inches, 1440 x 3216 px, 120 Hz Display with Punch Hole           10
6.58 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch    10
6.78 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           9
6.5 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            9
6.5 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        9
6.6 inches, 1080 x 2408 px Display with Water Drop Notch              9
6.6 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch       9
6.67 inches, 1080 x 2400 px Display with Punch Hole                   9
6.7 inches, 1080 x 2400 px Display with Punch Hole                    8
6.55 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            8
6.58 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      8
6.53 inches, 1080 x 2340 px Display with Water Drop Notch             7
6.58 inches, 1080 x 2408 px Display with Water Drop Notch             7
6.58 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      7
6.59 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           7
6.6 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole            7
6.6 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch      7
6.67 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           6
6.1 inches, 1170 x 2532 px Display with Small Notch                   6
6.5 inches, 720 x 1600 px, 90 Hz Display with Punch Hole              6
6.4 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch       6
6.44 inches, 1080 x 2400 px Display with Water Drop Notch             6
12 MP + 12 MP Dual Rear & 12 MP Front Camera                          6
6.73 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           6
6.44 inches, 1080 x 2404 px, 90 Hz Display with Water Drop Notch      5
6.56 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch       5
6.67 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           5
6.4 inches, 1080 x 2400 px Display with Punch Hole                    5
6.56 inches, 720 x 1612 px Display with Water Drop Notch              5
6.8 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            5
6.67 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           5
6.6 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            5
6.5 inches, 720 x 1560 px Display with Water Drop Notch               5
6.6 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            4
6.4 inches, 1080 x 2340 px Display with Water Drop Notch              4
6.56 inches, 720 x 1600 px Display with Water Drop Notch              4
5000 mAh Battery with 33W Fast Charging                               4
6.7 inches, 720 x 1600 px Display with Water Drop Notch               4
6.7 inches, 1080 x 2400 px Display with Water Drop Notch              4
6.78 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           4
6.78 inches, 1080 x 2448 px, 165 Hz Display                           4
6.56 inches, 1080 x 2376 px, 120 Hz Display with Punch Hole           4
6.35 inches, 720 x 1544 px Display with Water Drop Notch              4
6.5 inches, 1600 x 720 px Display with Water Drop Notch               4
6.67 inches, 2400 x 1080 px, 120 Hz Display with Punch Hole           4
6.7 inches, 1290 x 2796 px, 120 Hz Display                            4
6.73 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           3
6.7 inches, 1284 x 2778 px, 120 Hz Display with Small Notch           3
6.4 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            3
6.78 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           3
6.6 inches, 2460 x 1080 px, 90 Hz Display with Punch Hole             3
6.43 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           3
6.6 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        3
6.7 inches, 2400 x 1080 px Display with Punch Hole                    3
6.51 inches, 1600 x 720 px Display with Punch Hole                    3
5000 mAh Battery with 120W Fast Charging                              3
6.6 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch        3
6.44 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     3
5 inches, 854 x 480 px Display                                        3
6.6 inches, 720 x 1600 px Display with Water Drop Notch               3
6.8 inches, 1116 x 2480 px, 120 Hz Display                            3
6.8 inches, 1080 x 2460 px Display with Punch Hole                    3
6.78 inches, 1440 x 3200 px, 144 Hz Display with Punch Hole           3
6.1 inches, 1170 x 2532 px, 120 Hz Display with Large Notch           3
8.03 inches, 1916 x 2160 px, 120 Hz Display                           3
6.1 inches, 1179 x 2556 px, 120 Hz Display                            3
5000 mAh Battery                                                      3
6.44 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      3
6.7 inches, 1284 x 2778 px Display with Small Notch                   3
5000 mAh Battery with 18W Fast Charging                               3
6.1 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.44 inches, 1080 x 2408 px Display with Water Drop Notch             3
6.6 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.6 inches, 1080 x 2408 px, 90 Hz Display with Punch Hole             3
6.8 inches, 1440 x 3080 px, 120 Hz Display with Punch Hole            3
6.6 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole             3
6.47 inches, 1080 x 2400 px Display with Punch Hole                   3
6.59 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole            3
7.1 inches, 1792 x 1920 px, 120 Hz Display with Punch Hole            3
6.44 inches, 1080 x 2400 px, 90 Hz Display with Small Notch           2
6.5 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
6.71 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole           2
6.22 inches, 720 x 1520 px Display with Water Drop Notch              2
6.44 inches, 1080 x 2400 px, 90 Hz Display with Dual Punch Hole       2
6.49 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            2
6.44 inches, 1080 x 2400 px Display with Small Notch                  2
6.5 inches, 1644 x 3840 px, 120 Hz Display                            2
6.4 inches, 1080 x 2340 px Display with Punch Hole                    2
6.6 inches, 1080 x 2400 px Display with Water Drop Notch              2
6.5 inches, 720 x 1600 px Display with Punch Hole                     2
6.8 inches, 1440 x 3040 px Display with Punch Hole                    2
6.8 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole            2
6.58 inches, 1080 x 2408 px, 90 Hz Display with Punch Hole            2
6.1 inches, 828 x 1792 px Display with Large Notch                    2
6.6 inches, 1612 x 720 px Display with Water Drop Notch               2
6 inches, 1080 x 2160 px Display                                      2
5.45 inches, 720 x 1440 px Display                                    2
6.51 inches, 720 x 1600 px Display with Punch Hole                    2
6.58 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.8 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            2
6.7 inches, 1080 x 2388 px, 90 Hz Display with Punch Hole             2
6.6 inches, 1080 x 2412 px, 144 Hz Display with Punch Hole            2
6.4 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            2
7.6 inches, 1812 x 2176 px, 120 Hz Display with Punch Hole            2
6.7 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            2
5.5 inches, 1080 x 1920 px Display                                    2
6.6 inches, 2408 x 1080 px Display with Water Drop Notch              2
6.44 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      2
6.73 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.72 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.4 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        2
6.7 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole             2
6.71 inches, 720 x 1650 px Display with Water Drop Notch              2
6.78 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole           2
6.57 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           2
6.7 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
12 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera                2
4.7 inches, 750 x 1334 px Display                                     2
6.2 inches, 720 x 1520 px Display with Water Drop Notch               2
6.55 inches, 720 x 1612 px Display with Water Drop Notch              2
6.6 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch      2
6.3 inches, 1080 x 2340 px Display with Water Drop Notch              2
6.1 inches, 1080 x 2520 px, 120 Hz Display                            2
6.73 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           2
6.56 inches, 1080 x 2376 px, 90 Hz Display with Small Notch           2
6.28 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.5 inches, 720 x 1560 px Display with Small Notch                    2
6.5 inches, 1080 x 2400 px Display with Water Drop Notch              2
6.56 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       2
6 inches, 720 x 1440 px Display                                       2
6.71 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           2
6.22 inches, 1520 x 720 px Display with Water Drop Notch              2
6.5 inches, 1080 x 2400 px Display with Punch Hole                    2
6.8 inches, 1080 x 2460 px Display                                    2
6.58 inches, 1200 x 2640 px, 90 Hz Display with Dual Punch Hole       1
6.7 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            1
6.2 inches, 1440 x 2960 px Display                                    1
6.39 inches, 1080 x 2316 px Display                                   1
6.6 inches, 1080 x 2400 px, 90 Hz Display with Dual Punch Hole        1
6.3 inches, 1080 x 2280 px Display                                    1
6.91 inches, 1080 x 2460 px Display with Punch Hole                   1
6 inches, 720 x 1600 px Display                                       1
6.95 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           1
7.4 inches, 1440 x 3200 px Display                                    1
6.4 inches, 1080 x 2408 px Display with Water Drop Notch              1
6.56 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      1
6.43 inches, 1080 x 2400 px Display with Dual Punch Hole              1
6.38 inches, 1080 x 2340 px Display with Water Drop Notch             1
6.67 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch     1
6.67 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole           1
6.76 inches, 1440 x 3200 px, 120 Hz Display with Small Notch          1
7.8 inches, 2200 x 2480 px, 120 Hz Display with Punch Hole            1
6.62 inches, 1080 x 2412 px, 144 Hz Display with Water Drop Notch     1
6.06 inches, 1170 x 2532 px Display with Punch Hole                   1
6.1 inches, 720 x 1520 px Display with Water Drop Notch               1
8.01 inches, 1860 x 2480 px, 90 Hz Display                            1
6.6 inches, 1288 x 2700 px, 120 Hz Display with Punch Hole            1
6.7 inches, 1080 x 2520 px, 90 Hz Display with Punch Hole             1
6.44 inches, 1080 x 2400 px Display with Dual Punch Hole              1
6.2 inches, 1440 x 3200 px Display with Punch Hole                    1
4000 mAh Battery with 20W Fast Charging                               1
4000 mAh Battery with Fast Charging                                   1
6.78 inches, 1200 x 2652 px, 120 Hz Display with Punch Hole           1
12 MP Rear & 10.8 MP Front Camera                                     1
6.5 inches, 1080 x 2412 px, 144 Hz Display                            1
7 inches, 1440 x 3080 px, 120 Hz Display with Punch Hole              1
6.43 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole            1
6.5 inches, 1080 x 2340 px Display                                    1
6.95 inches, 1080 x 2460 px Display with Punch Hole                   1
6.6 inches, 1260 x 2730 px, 240 Hz Display with Punch Hole            1
6.67 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole            1
4532 mAh Battery with Fast Charging                                   1
6.83 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           1
6.6 inches, 720 x 1612 px Display with Water Drop Notch               1
6.9 inches, 1080 x 2460 px, 120 Hz Display                            1
6.67 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           1
6.58 inches, 1080 x 2412 px, 120 Hz Display with Water Drop Notch     1
6.8 inches, 1080 x 2400 px, 165 Hz Display                            1
6.51 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.4 inches, 720 x 1600 px Display with Water Drop Notch               1
6.34 inches, 1080 x 2400 px Display with Punch Hole                   1
6.5 inches, 1600 x 720 px, 90 Hz Display with Punch Hole              1
6.09 inches, 1520 x 720 px Display with Water Drop Notch              1
6.5 inches, 1440 x 3168 px Display with Water Drop Notch              1
4000 mAh Battery                                                      1
6.53 inches, 1176 x 2400 px Display with Large Notch                  1
6.4 inches, 720 x 1560 px Display with Punch Hole                     1
6.1 inches, 1560 x 720 px Display with Water Drop Notch               1
8 inches, 2200 x 2480 px Display                                      1
6 inches, 2220 x 1080 px Display                                      1
5.2 inches, 720 x 1280 px Display                                     1
5180 mAh Battery with 10W Fast Charging                               1
6.75 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
6.82 inches, 720 x 1560 px Display with Punch Hole                    1
5.86 inches, 720 x 1520 px Display with Large Notch                   1
6.43 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           1
6.6 inches, 1080 x 2400 px, 144 Hz Display                            1
6.73 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole           1
5 inches, 1080 x 1920 px Display                                      1
6.39 inches, 1080 x 2340 px Display                                   1
6.78 inches, 1080 x 2460 px Display with Water Drop Notch             1
5.9 inches, 1080 x 2340 px Display with Water Drop Notch              1
5100 mAh Battery with 18W Fast Charging                               1
6.8 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.67 inches, 1220 x 2712 px, 144 Hz Display with Punch Hole           1
6.51 inches, 1600 x 720 px, 90 Hz Display with Water Drop Notch       1
6.8 inches, 720 x 1600 px Display with Punch Hole                     1
6.78 inches, 1080 x 2480 px, 90 Hz Display with Punch Hole            1
4 inches, 480 x 640 px Display                                        1
6.5 inches, 1080 x 2400 px, 144 Hz Display                            1
6.71 inches, 1080 x 2400 px Display with Punch Hole                   1
4300 mAh Battery with 30W Fast Charging                               1
5.3 inches, 720 x 1480 px Display                                     1
6 inches, 1080 x 2520 px, 90 Hz Display                               1
6.53 inches, 1080 x 2340 px Display with Punch Hole                   1
6.7 inches, 1440 x 3040 px Display                                    1
6.7 inches, 1440 x 3200 px Display with Punch Hole                    1
5.84 inches, 1080 x 2280 px Display with Small Notch                  1
6.67 inches, 1080 x 2412 px, 120 Hz Display with Water Drop Notch     1
7000 mAh Battery                                                      1
6.43 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           1
6.52 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
7.2 inches, 1440 x 1920 px Display                                    1
6.8 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole             1
6.62 inches, 2400 x 1080 px, 120 Hz Display with Punch Hole           1
6 inches, 1080 x 2520 px Display                                      1
6.67 inches, 2400 x 1080 px, 144 Hz Display with Punch Hole           1
6.53 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
6.3 inches, 1080 x 2400 px Display with Punch Hole                    1
6000 mAh Battery with 15W Fast Charging                               1
6.8 inches, 1080 x 2460 px Display with Water Drop Notch              1
6.2 inches, 720 x 1680 px Display                                     1
6.76 inches, 1344 x 2772 px, 120 Hz Display with Punch Hole           1
6.8 inches, 1080 x 2520 px, 120 Hz Display with Punch Hole            1
6.95 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole            1
6.7 inches, 720 x 1650 px Display with Punch Hole                     1
8.02 inches, 1914 x 2160 px, 120 Hz Display with Punch Hole           1
6.3 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.7 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch       1
6.9 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole            1
6.1 inches, 828 x 1792 px Display                                     1
5.4 inches, 1080 x 2340 px Display with Large Notch                   1
6.9 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole             1
5.42 inches, 1080 x 2340 px Display with Punch Hole                   1
6.36 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
4250 mAh Battery with 33W Fast Charging                               1
6.6 inches, 1600 x 720 px Display with Punch Hole                     1
6 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole              1
6.81 inches, 1080 x 2388 px Display                                   1
7.8 inches, 1440 x 1920 px Display                                    1
6.82 inches, 720 x 1640 px, 90 Hz Display with Punch Hole             1
6.5 inches, 720 x 1600 px, 120 Hz Display with Punch Hole             1
6.53 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             1
6.2 inches, 1520 x 720 px Display with Water Drop Notch               1
6.55 inches, 1612 x 720 px, 90 Hz Display with Water Drop Notch       1
6.83 inches, 1200 x 2860 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1200 x 2400 px, 120 Hz Display with Punch Hole            1
2800 mAh Battery with Fast Charging                                   1
6.4 inches, 1440 x 3040 px Display with Punch Hole                    1
6.7 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            1
6.5 inches, 1600 x 720 px, 90 Hz Display with Water Drop Notch        1
6.82 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1

In [49]:
(982/1020)*100

96.27450980392157

In [50]:
df1

      index                                              model   price  \
0         4                                      OnePlus 11 5G   54999
1         5                          OnePlus Nord CE 2 Lite 5G   19989
2         6                              Samsung Galaxy A14 5G   16499
3         7                               Motorola Moto G62 5G   14999
4         8                                 Realme 10 Pro Plus   24999
5         9            Samsung Galaxy F23 5G (6GB RAM + 128GB)   16999
6        10                                    Apple iPhone 14   65999
7        11                      Xiaomi Redmi Note 12 Pro Plus   29999
8        12                                    Nothing Phone 1   26749
9        13                                 OnePlus Nord 2T 5G   28999
10       14                                      Realme 10 Pro   18999
11       15                                           Oppo A78   18999
12       16                        Xiaomi Redmi Note 12 Pro 5G   24762
13       17                       Vivo T1 5G (6GB RAM + 128GB)   16990
14       18                        Samsung Galaxy S23 Ultra 5G  114990
15       19                                    Apple iPhone 13   62999
16       20                                           Vivo Y16    9999
17       21                               OPPO Reno 9 Pro Plus   45999
18       22                                     OnePlus 10R 5G   32999
19       23                                           Vivo Y22   14499
20       24                                        OnePlus 11R   39999
21       25                                    Vivo V25 Pro 5G   35999
22       26                                     Poco X4 Pro 5G   14999
23       27                               Xiaomi Redmi Note 12   17859
24       28                                       Vivo V26 Pro   42990
25       29                           Samsung Galaxy S20 FE 5G   31239
26       30        OnePlus Nord CE 2 Lite 5G (8GB RAM + 128GB)   21995
27       31                            Apple iPhone 14 Pro Max  129990
28       32                                        Vivo V25 5G   27999
29       33                                     OnePlus 11 Pro   69999
30       34                    Realme 10 Pro (8GB RAM + 128GB)   19999
31       35                                        Poco X5 Pro   20999
32       36                                           Vivo V27   27990
33       37                                    Apple iPhone 11   38999
34       38                              Samsung Galaxy M53 5G   23790
35       39                           Samsung Galaxy S21 FE 5G   39999
36       40                                       Oppo Reno 8T   29990
37       41                        Samsung Galaxy S22 Ultra 5G   91999
38       42                    Xiaomi Redmi Note 12 Pro Max 5G   32999
39       43                                     OPPO Reno 9 5G   28499
40       44                               OnePlus Nord CE 3 5G   21999
41       45                   Xiaomi Redmi Note 11 Pro Plus 5G   19999
42       46                         Motorola Edge 20 Fusion 5G   18999
43       47               Realme 10 Pro Plus (8GB RAM + 256GB)   27999
44       48                                           Vivo Y35   18499
45       49                              Samsung Galaxy M33 5G   17478
46       50                               Xiaomi Redmi Note 11   11936
47       51                                         Realme C33    8950
48       52                          Vivo Y16 (4GB RAM + 64GB)   12489
49       53                              Samsung Galaxy A74 5G   42999
50       54            Samsung Galaxy A14 5G (6GB RAM + 128GB)   18999
51       55                                      iQOO Neo 7 5G   29999
52       56                                    Jio JioPhone 5G   11990
53       57                               Motorola Moto G82 5G   18999
54       58                                          Realme 10   13999
55       59                                       Realme 9i 5G   14965
56       60                               Apple iPhone 14 Plus   74999
57       61                              Xiaomi Redmi Note 10S   10999
58       62                            Samsung Galaxy S23 Plus   84990
59       63                                  Motorola Moto G32   10499
60       64                        Xiaomi Redmi Note 13 Pro 5G   17990
61       65                                           Vivo S16   29990
62       66                                 Samsung Galaxy A23   18499
63       67                         Vivo Y22 (6GB RAM + 128GB)   16499
64       68                   Poco M4 Pro 5G (6GB RAM + 128GB)   14999
65       69                                       Vivo S16 Pro   35499
66       70                                  OnePlus 10 Pro 5G   60999
67       71   Xiaomi Redmi Note 12 Pro Plus (12GB RAM + 256GB)   32999
68       72                              Samsung Galaxy F23 5G   15999
69       73                                   Oppo Find N Fold   99990
70       74                                          OPPO A17K    9499
71       75                     Vivo V23 5G (12GB RAM + 256GB)   27994
72       76                                    iQOO Z6 Lite 5G   13989
73       77                                        OnePlus 10T   44999
74       78          Xiaomi Redmi Note 10T 5G (6GB RAM +128GB)   13999
75       79                                     Gionee G13 Pro    6190
76       80                                Apple iPhone 13 Pro  119900
77       81                                       OPPO F22 Pro   27660
78       82                              Samsung Galaxy A34 5G   24999
79       83                  Xiaomi Redmi 10A (4GB RAM + 64GB)    8388
80       84                               Motorola Moto G72 4G   15999
81       85            Samsung Galaxy A14 5G (8GB RAM + 128GB)   20999
82       86                                        Realme 9 5G   13999
83       87                       Vivo T1 5G (8GB RAM + 128GB)   19990
84       88                              Samsung Galaxy M13 5G   13999
85       89                                Motorola Edge 30 5G   22999
86       90                              Samsung Galaxy A23 5G   22999
87       91                                        OPPO K10 5G   16999
88       92             Xiaomi Redmi Note 11 (6GB RAM + 128GB)   14290
89       93                              Samsung Galaxy A73 5G   41999
90       94                                      Vivo Y21 2021   13489
91       95                      OnePlus Ace Racing Edition 5G   22990
92       96                Motorola Moto G62 (8GB RAM + 128GB)   16499
93       97                               Vivo X90 Pro Plus 5G   73999
94       98                        Realme C33 (4GB RAM + 64GB)    9999
95       99                                          Realme 9i   12499
96      100                                           OPPO A17   12499
97      101                                         iQOO 11 5G   59999
98      102                                     Vivo X Fold 5G  106990
99      103                                         Vivo T1 5G   15990
100     104                                Apple iPhone 14 Pro  119990
101     105                    Xiaomi Redmi Note 11 Pro Max 5G   19999
102     106                              Motorola Moto S30 Pro   23990
103     107                                         Realme 10s   12999
104     108                               OPPO F19 Pro Plus 5G   19990
105     109                                   Xiaomi 13 Pro 5G   58990
106     110                                       Vivo V27 Pro   43999
107     111                              Samsung Galaxy S22 5G   49999
108     112                      Vivo T1 44W (6GB RAM + 128GB)   15999
109     113                  OnePlus 10R 5G (12GB RAM + 256GB)   36999
110     114                                   Tecno Phantom X2   39999
111     115                                    Apple iPhone 12   51999
112     116                               Xiaomi Redmi K50i 5G   22999
113     117                              Samsung Galaxy A53 5G   31999
114     118                                    Xiaomi Redmi A1    6171
115     119                                      OPPO Reno8 5G   29340
116     120            Samsung Galaxy M53 5G (8GB RAM + 128GB)   25289
117     121                                     iQOO Z6 Pro 5G   21788
118     122                                     Tesla Pi Phone   69999
119     123                                 Samsung Galaxy S23   70990
120     124                            Motorola Edge 30 Pro 5G   34999
121     125                 OnePlus Nord 2T (12GB RAM + 256GB)   33900
122     126                                    Google Pixel 6A   29999
123     127                             Infinix Note 12 Pro 5G   18999
124     128            Samsung Galaxy M33 5G (8GB RAM + 128GB)   19499
125     129                                        Vivo V23 5G   24994
126     130                                  Motorola Moto G42   10999
127     131        OnePlus Nord CE 2 Lite 5G (8GB RAM + 256GB)   24999
128     132                              Samsung Galaxy A33 5G   25999
129     133                                    Google Pixel 7A   34990
130     134                           Xiaomi Redmi 11 Prime 5G   13466
131     135                          Xiaomi Redmi Note 10 Lite    9999
132     136                                  Motorola Moto E40    7999
133     137                  Nothing Phone 1 (8GB RAM + 256GB)   28249
134     138                   Poco X4 Pro 5G (6GB RAM + 128GB)   16499
135     139  Xiaomi Redmi Note 11 Pro Plus 5G (8GB RAM + 25...   22999
136     140                            Apple iPhone 11 (128GB)   46999
137     141                       Realme C35 (6GB RAM + 128GB)   13999
138     142                                           OPPO K10   13490
139     143                                      iQOO Neo 6 5G   28999
140     144                                         iQOO Z6 5G   15499
141     145                                 OPPO Reno 9 Pro 5G   39999
142     146                                     Poco M4 Pro 5G   12999
143     147                                        Jio Phone 3    4499
144     148                                     OnePlus Clover   14999
145     149                                 Samsung Galaxy F04    8499
146     150                                             iQOO 7   24990
147     151                              Samsung Galaxy M34 5G   16999
148     152                                    Xiaomi Redmi 10    9589
149     153                               Apple iPhone 12 Mini   40999
150     154             Xiaomi Redmi Note 12 (6GB RAM + 128GB)   19988
151     155                                  Motorola Moto G52   11999
152     156                            Apple iPhone 15 Pro Max  142990
153     157                                           Oppo A98   30990
154     158                               Infinix Zero 5G 2023   19499
156     160                                         Realme C30    5299
157     161                                    OPPO F21 Pro 5G   25969
158     162                                      Realme 11 Pro   28999
159     163                                    Oppo Find N2 5G   94990
160     164                                        Realme 9 4G   14999
161     165                                         Cola Phone   14999
162     166                            Apple iPhone 13 Pro Max  129900
163     167                              Oppo Reno 10 Pro Plus   58990
164     168                                        Vivo X90 5G   41990
165     169                                 Samsung Galaxy F13   10999
166     170            Xiaomi Redmi Note 10S (6GB RAM + 128GB)   11999
167     171                        Realme 10 (8GB RAM + 128GB)   16999
168     172                                       iQOO 9 SE 5G   30990
169     173                                     Infinix Hot 20   17999
170     174                                        Letv Y1 Pro    5499
171     175                    Xiaomi Redmi Note 13 Pro Max 5G   20499
172     176                             Realme Narzo 50 Pro 5G   20490
173     177                                        OPPO A74 5G   15490
174     178                                     Apple iPhone 9   29990
175     179                     iQOO Z6 Lite (6GB RAM + 128GB)   15499
176     180                             Xiaomi Redmi Note 11SE   11999
177     181                                    Realme Narzo 50   10999
178     182                                        Vivo Y75 5G   21990
179     183                        Vivo V25 (12GB RAM + 256GB)   31999
180     184                                     POCO M4 Pro 4G   11999
181     185                                 Infinix Zero Ultra   36999
182     186                                Tecno Spark Go 2023    6999
183     187                                  Motorola Moto X40   39999
184     188                              Samsung Galaxy F24 5G   14999
185     189                                       Realme 10 5G   14499
186     190                                  OnePlus Nord 3 5G   27999
187     191                Motorola Moto G82 (8GB RAM + 128GB)   20499
188     192                                      iKall Z19 Pro    8099
189     193                                       LeEco S1 Pro   10999
190     194                                         Realme C2s    3499
191     195                                     Duoqin F22 Pro    9990
192     196                              Samsung Galaxy M54 5G   34999
193     197                                       Nokia N73 5G   46999
194     198                         Motorola Edge 30 Fusion 5G   39999
195     199                                         Realme C35   11828
196     200            OPPO Reno 8 Pro House of Dragon Edition   45999
197     201                          OnePlus Nord CE 3 Lite 5G   18999
198     202                   Poco X4 Pro 5G (8GB RAM + 128GB)   17999
199     203                                 Samsung Galaxy M04    8499
200     204                                          OPPO A77s   17999
201     205                                 Samsung Galaxy A13   14450
202     206                             Motorola Edge 30 Ultra   54999
203     207                                 Xiaomi 13 Ultra 5G   71999
204     208                Motorola Moto G52 (6GB RAM + 128GB)   12999
205     209                                         Poco M4 5G   11499
206     210                 Nothing Phone 1 (12GB RAM + 256GB)   35999
207     211                              Samsung Galaxy A54 5G   34999
208     212                                       Tecno Pova 4   11999
209     213         Xiaomi Redmi Note 12 Pro (8GB RAM + 256GB)   27994
210     214                    Apple iPhone 14 Pro Max (256GB)  139990
211     215                    Vivo V25 Pro (12GB RAM + 256GB)   39999
212     216                      Realme 9 5G (6GB RAM + 128GB)   15499
213     217                                    Realme 9 Pro 5G   18999
214     218                                      Lava Blaze 5G   10999
215     219                                          Honor X9a   27999
216     220                              Google Pixel 7 Pro 5G   81999
217     221                                       Tecno Pova 3    9999
218     222                                    Vivo V23 Pro 5G   31994
219     223                                Samsung Galaxy A04e    9299
220     224                                   Xiaomi Redmi K60   29990
221     225                               Realme 9 Pro Plus 5G   25900
222     226                     Realme 9i 5G (6GB RAM + 128GB)   16999
223     227              Motorola Edge 30 5G (8GB RAM + 128GB)   24999
224     228              Xiaomi Redmi Note 11 (6GB RAM + 64GB)   12188
225     229                                           Vivo Y02    8999
226     230                          POCO C31 (4GB RAM + 64GB)    7499
227     231                                 Realme Narzo 50 5G   17999
228     232                                   Realme GT Neo 3T   24999
229     233                                 OPPO Reno 8 Pro 5G   45999
230     234               OnePlus 10 Pro 5G (12GB RAM + 256GB)   65499
231     235                                     iQOO 11 Pro 5G   58990
232     236                                        Vivo T1x 4G   11999
233     237                              Xiaomi Redmi 10 Power   11999
234     238                                           OPPO A58   18990
235     239                                        Vivo T1 44W   14499
236     240                               Xiaomi Mix Fold 2 5G  106990
237     241                          Vivo Y16 (3GB RAM + 64GB)   10499
238     242                                      OPPO Reno 8 Z   26990
239     243                                        Vivo Y75 4G   19990
240     244                      Xiaomi Redmi Note 12 Explorer   24999
241     245                      OPPO A57 4G (4GB RAM + 64 GB)   13969
242     246                              Samsung Galaxy A75 5G   44999
243     247                   Vivo T1 Pro 5G (8GB RAM + 128GB)   24999
244     248                                  Google Pixel 7 5G   53100
245     249         Xiaomi Redmi Note 11T 5G (6GB RAM + 128GB)   16999
246     250                                   OPPO F21s Pro 4G   21899
247     251                            Apple iPhone 14 (256GB)   75999
248     252                                  Motorola Moto G73   25999
249     253                           Nubia Red Magic 8 Pro 5G   46990
250     254                                  Motorola Moto G31    9999
251     255                               Tecno Phantom X2 Pro   49999
252     256                                    Infinix Zero 20   17999
253     257                       iQOO Z6 5G (6GB RAM + 128GB)   16940
254     258                        Xiaomi Redmi Note 11 Pro 5G   17990
255     259                                        OPPO A1 Pro   20990
256     260                           Samsung Galaxy S22 FE 5G   51999
257     261                         Samsung Galaxy S22 Plus 5G   64449
258     262                                           Vivo U3x    8990
259     263                                  Motorola Moto G23   19999
260     264                       Poco M4 5G (6GB RAM + 128GB)   13499
261     265                                      Tecno Pova 5G   15499
262     266                                           POCO C31    6499
263     267                                   Apple iPhone XR2   71999
264     268               Samsung Galaxy A53 (8GB RAM + 256GB)   36499
265     269                                 Infinix Note 12 5G   15999
266     270                                  OPPO Reno7 Pro 5G   31994
267     271                                      OnePlus Ace 2   34999
268     272                             Redmi Note 11 Pro 2023   18999
269     273                                    Nothing Phone 2   39990
270     274               Samsung Galaxy A32 (8GB RAM + 128GB)   16499
272     276                                 Google Pixel 6 Pro   54300
273     277                            Infinix Note 12i (2022)    9999
274     278         Xiaomi Redmi 11 Prime 5G (6GB RAM + 128GB)   15990
275     279  Xiaomi Redmi Note 11 Pro Plus 5G (8GB RAM + 12...   22700
276     280                                   Xiaomi 12 Pro 5G   50990
277     281                               Apple iPhone 13 Mini   64900
278     282                     Tecno Pova 3 (6GB RAM + 128GB)   13799
279     283                        Realme C31 (4GB RAM + 64GB)    8999
280     284                            Asus ROG Phone 6 Pro 5G   89999
281     285                                       Vivo V23e 5G   21994

In [51]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 982 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      982 non-null    int64
 1   model      982 non-null    object
 2   price      982 non-null    int32
 3   rating     879 non-null    float64
 4   sim        982 non-null    object
 5   processor  982 non-null    object
 6   ram        982 non-null    object
 7   battery    951 non-null    object
 8   display    982 non-null    object
 9   camera     982 non-null    object
 10  card       982 non-null    object
 11  os         981 non-null    object
dtypes: float64(1), int32(1), int64(1), object(9)
memory usage: 128.2+ KB

In [52]:
brand_names = df1['model'].str.split(' ').str.get(0)

In [53]:
df1.insert(1,'brand_name',brand_names)

In [54]:
df1['brand_name'] = df1['brand_name'].str.lower()

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\3193801224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['brand_name'] = df1['brand_name'].str.lower()

In [55]:
has_5g = df1['sim'].str.contains('5G')
has_nfc = df1['sim'].str.contains('NFC')
has_ir_blaster = df1['sim'].str.contains('IR Blaster')

In [56]:
df1.insert(6,'has_5g',has_5g)
df1.insert(7,'has_nfc',has_nfc)
df1.insert(8,'has_ir_blaster',has_ir_blaster)

In [57]:
processor_name = df1['processor'].str.split(',').str.get(0)

In [58]:
num_cores = df1['processor'].str.split(',').str.get(1)

In [59]:
processor_speed = df1['processor'].str.split(',').str.get(2)

In [60]:
df1.insert(10,'processor_name',processor_name)
df1.insert(11,'num_cores',num_cores)
df1.insert(12,'processor_speed',processor_speed)

In [61]:
df1['processor_name'] = df1['processor_name'].str.strip()

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\1632474951.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['processor_name'] = df1['processor_name'].str.strip()

In [62]:
temp_df = df1[df1['processor_name'].str.contains('Core')][['processor_name', 'num_cores',	'processor_speed']].shift(1,axis=1)

In [63]:
temp_df.shape

(20, 3)

In [64]:
df1.loc[temp_df.index,['processor_name', 'num_cores',	'processor_speed']] = temp_df.values

In [65]:
df1.loc[856]

index                                                860
brand_name                                       samsung
model                            Samsung Galaxy A01 Core
price                                               4999
rating                                               NaN
sim                       Dual Sim, 3G, 4G, VoLTE, Wi-Fi
has_5g                                             False
has_nfc                                            False
has_ir_blaster                                     False
processor          (28 nm), Quad Core, 1.5 GHz Processor
processor_name                                   (28 nm)
num_cores                                      Quad Core
processor_speed                        1.5 GHz Processor
ram                              1 GB RAM, 16 GB inbuilt
battery                                 3000 mAh Battery
display                5.3 inches, 720 x 1480 px Display
camera                     8 MP Rear & 5 MP Front Camera
card                               Memory Card Supported
os                                           Android v10
Name: 856, dtype: object

In [66]:
df1.loc[856,'processor_name'] = 'Mediatek MT6739'

In [67]:
processor_brand = df1['processor_name'].str.split(' ').str.get(0).str.lower()

In [68]:
df1.insert(11,'processor_brand',processor_brand)

In [69]:
df1['num_cores'] = df1['num_cores'].str.strip()

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\2483753889.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['num_cores'] = df1['num_cores'].str.strip()

In [70]:
df1['num_cores'] = df1['num_cores'].str.replace('Octa Core Processor','Octa Core').str.replace('Hexa Core Processor','Hexa Core')

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\3285793486.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['num_cores'] = df1['num_cores'].str.replace('Octa Core Processor','Octa Core').str.replace('Hexa Core Processor','Hexa Core')

In [71]:
df1['processor_speed'] = df1['processor_speed'].str.strip().str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0).astype(float)

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\825004774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['processor_speed'] = df1['processor_speed'].str.strip().str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0).astype(float)

In [72]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,display,camera,card,os
0,4,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,snapdragon,Octa Core,3.2,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,5,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,snapdragon,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,6,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,exynos,Octa Core,2.4,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,7,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,snapdragon,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,8,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity 1080,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [73]:
ram_capacity = df1['ram'].str.strip().str.split(',').str.get(0).str.findall(r'\b(\d+)\b').str.get(0)

In [74]:
df1.insert(16,'ram_capacity',ram_capacity)

In [75]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,processor_brand,num_cores,processor_speed,ram,battery,ram_capacity,display,camera,card,os
0,4,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,snapdragon,Octa Core,3.2,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,12,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,5,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,snapdragon,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,6,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,6,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",...,exynos,Octa Core,2.4,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,4,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,7,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",...,snapdragon,Octa Core,2.2,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,6,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,8,realme,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 1080, Octa Core, 2.6 GHz Processor",...,dimensity,Octa Core,2.6,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,6,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [76]:
internal_memory = df1['ram'].str.strip().str.split(',').str.get(1).str.strip().str.findall(r'\b(\d+)\b').str.get(0)

In [77]:
df1.insert(17,'internal_memory',internal_memory)

In [78]:
df1['ram_capacity'] = df1['ram_capacity'].astype(float)

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\2073605403.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ram_capacity'] = df1['ram_capacity'].astype(float)

In [79]:
df1.drop([486,627],inplace=True)

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\2098217776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([486,627],inplace=True)

In [80]:
df1.loc[[483], ['ram_capacity','internal_memory']] = [12.0,'512']

In [81]:
df1['ram_capacity'].value_counts()

ram_capacity
8.0     339
6.0     234
4.0     215
12.0     86
3.0      54
2.0      32
16.0      9
1.0       7
18.0      2
64.0      2
Name: count, dtype: int64

In [82]:
df1['internal_memory'] = df1['internal_memory'].astype(float)

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\3988935729.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['internal_memory'] = df1['internal_memory'].astype(float)

In [83]:
temp_df = df1[df1['internal_memory'] == 1]

In [84]:
df1.loc[temp_df.index,'internal_memory'] = 1024

In [85]:
df1['internal_memory'].value_counts()

internal_memory
128.0     523
64.0      191
256.0     157
32.0       67
512.0      22
16.0       12
1024.0      5
8.0         1
Name: count, dtype: int64

In [86]:
battery_capacity = df1['battery'].str.strip().str.split('with').str.get(0).str.strip().str.findall(r'\b(\d+)\b').str.get(0).astype(float)

In [87]:
df1.insert(16,'battery_capacity',battery_capacity)

In [88]:
fast_charging = df1['battery'].str.strip().str.split('with').str.get(1).str.strip().str.findall(r'\d{2,3}')

In [89]:
df1.insert(17,'fast_charging',fast_charging)

In [90]:
def fast_charging_extractor(item):

  if type(item) == list:
    if len(item) == 1:
      return item[0]
    else:
      return 0
  else:
    return -1

In [91]:
df1['fast_charging'] = df1['fast_charging'].apply(fast_charging_extractor).astype(int)

C:\Users\abbim\AppData\Local\Temp\ipykernel_10576\3894870647.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['fast_charging'] = df1['fast_charging'].apply(fast_charging_extractor).astype(int)

In [92]:
screen_size = df1['display'].str.strip().str.split(',').str.get(0).str.strip().str.split(' ').str.get(0).astype(float)

ValueError: could not convert string to float: '5000\u2009mAh'

In [ ]:
df1.insert(21,'screen_size',screen_size)

In [ ]:
resolution = df1['display'].str.strip().str.split(',').str.get(1).str.strip().str.split('px').str.get(0)

In [ ]:
df1.insert(22,'resolution',resolution)

In [ ]:
refresh_rate = df1['display'].str.strip().str.split(',').str.get(2).str.strip().str.findall(r'\d{2,3}').str.get(0).apply(lambda x: 60 if pd.isna(x) else x).astype(int)

In [ ]:
df1.insert(22,'refresh_rate',refresh_rate)

In [ ]:
df1.head()

In [ ]:
def camera_extractor(text):

  if 'Quad' in text:
    return '4'
  elif 'Triple' in text:
    return '3'
  elif 'Dual' in text:
    return '2'
  elif 'Missing' in text:
    return 'Missing'
  else:
    return '1'

In [ ]:
num_rear_cameras = df1['camera'].str.strip().str.split('&').str.get(0).apply(camera_extractor)

In [ ]:
df1.insert(25,'num_rear_cameras',num_rear_cameras)

In [ ]:
num_front_cameras = df1['camera'].str.strip().str.split('&').str.get(1).str.strip().fillna('Missing').apply(camera_extractor)

In [ ]:
df1.insert(26,'num_front_cameras',num_front_cameras)

In [ ]:
df1.head()

In [ ]:
df1[df1['num_front_cameras'] == 'Missing']

In [ ]:
pd.set_option('display.max_columns',None)

In [ ]:
df1.head()

In [ ]:
#df1[df1['camera'] == 'Foldable Display, Dual Display']
df1.loc[69,'camera'] == '50 MP'

In [ ]:
temp_df = df1[df1['camera'] == 'Foldable Display, Dual Display']

In [ ]:
df1.loc[temp_df.index, 'camera'] = '50 MP'

In [ ]:
df1['primary_camera_rear'] = df1['camera'].str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0)

In [ ]:
df1['primary_camera_front'] = df1['camera'].str.split('&').str.get(1).str.strip().str.split(' ').str.get(0).str.replace('\u2009',' ').str.split(' ').str.get(0)

In [ ]:
df1.head()

In [ ]:
df1[df1['card'] == 'Memory Card (Hybrid)']

In [ ]:
df1.loc[temp_df.index, 'card'] = 'Not Specified'

In [ ]:
df1['extended_memory'] = df1['card'].apply(lambda x:'0' if 'Not' in x else x.split('upto')).str.get(-1).str.strip().str.replace('Memory Card Supported','Not Specified')

In [ ]:
df1.head()

In [ ]:
df1[df1['os'].str.contains('Memory Card')]

In [ ]:
df1.loc[temp_df.index, 'os'] = 'Not Specified'

In [ ]:
df1['os'].value_counts()

In [ ]:
def os_extractor(text):

  if 'Android' in text:
    return 'android'
  elif 'iOS' in text:
    return 'ios'
  elif 'Not Specified':
    return text
  elif 'Harmony' in text or 'Hongmeng' in text or 'EMUI' in text:
    return 'other'

In [ ]:
df1['os'] = df1['os'].apply(os_extractor)

In [ ]:
export_df = df1.drop(columns=['index','sim','processor','ram','battery','display','camera','card'])

In [ ]:
export_df.to_csv('smartphone_cleaned_v2.csv',index=False)